C*    *COMMON* *COUPL* - PARAMETERS FOR COUPLING.
C
      PARAMETER ( JPLEVC = 2)
      LOGICAL LWCOU, LWCOU2W
      COMMON /COUPL/ BETAMAX, ZALP, ALPHA, XKAPPA, XNLEV(JPLEVC),
     1               LWCOU, LWCOU2W
