C*    *COMMON* *CINP* USER INPUT: AREAS TO BE CHANGED, AND
C*                    SPECIAL OUTPUT POINTS.
C
      COMMON /CINP/ NOUT, XOUTW(IOUTA), XOUTS(IOUTA), XOUTE(IOUTA),
     1              XOUTN(IOUTA), NOUTD(IOUTA),
     2              OUTLONG(MOUTP), OUTLAT(MOUTP)
