C*    *COMMON* *CPBOUN* USED FOR THE COURSE GRID
C                       ORGANIZATION THE BOUNDARY POINTS.
C
      COMMON /CPBOUN/ IBOUNC, NBOUNC, IJARC(NBMAX), IGARC(NBMAX),
     1                DLAMAC, DPHIAC, AMOSOC, AMONOC, AMOEAC, AMOWEC,
     2                BLATC(NBMAX), BLNGC(NBMAX)
