C*    *COMMON* *FPBOUN* USED FOR THE FINE GRID
C                       ORGANIZATION THE BOUNDARY POINTS.
C
      COMMON /FPBOUN/ IBOUNF, NBOUNF, IJARF(NBMAX), IGARF(NBMAX),
     1                IBFL(NBMAX), IBFR(NBMAX), BFW(NBMAX)
