C*    *COMMON* *GRIDPAR*  GENERAL GRID INFORMATION.
C
      COMMON /GRIDPAR/ DELPHI, DELLAM(NGY),
     1                 SINPH(NGY), COSPH(NGY), NLONRGG(NGY),
     2                 IGL, IJS(NBLO), IJL2(NBLO), IJLS(NBLO),
     3                 IJL(NBLO), IJLT(NBLO)
