C*    *COMMON* *INTSPAR*  GRIDDED INTEGRATED SWELL PARAMETERS.
C
      COMMON /INTSPAR/ WHGTSG(NGX,NGY),WDIRSG(NGX,NGY),WMNFSG(NGX,NGY),
     1                 WHGTWG(NGX,NGY),WDIRWG(NGX,NGY),WMNFWG(NGX,NGY)
