C*    *COMMON* *INDNL* - INDICES AND WEIGHTS USED IN THE COMPUTATION
C                        OF THE NONLINEAR TRANSFER RATE.
C
      PARAMETER(KFRH=30)
      COMMON /INDNL/ IKP(NFRE+4), IKP1(NFRE+4),
     1               IKM(NFRE+4), IKM1(NFRE+4),
     2               K1W(NANG,2), K2W(NANG,2), K11W(NANG,2),
     3               K21W(NANG,2), AF11(NFRE+4), FKLAP(NFRE+4),
     4               FKLAP1(NFRE+4), FKLAM(NFRE+4), FKLAM1(NFRE+4),
     5               ACL1, ACL2,  CL11, CL21, DAL1, DAL2, FRH(KFRH)
