C*    *COMMON* *INTPAR*  GRIDDED INTEGRATED PARAMETER TOTAL SPECTRUM.
C
      COMMON /INTPAR/ WHGTTG(NGX,NGY), WDIRTG(NGX,NGY), WPKFTG(NGX,NGY),
     1                WMNFTG(NGX,NGY), USTARG(NGX,NGY), UDIRG(NGX,NGY),
     2                TAUWG (NGX,NGY), CDG   (NGX,NGY), 
     3                SMEANG(NGX,NGY), U10G  (NGX,NGY)
