C*    *COMMON* *MAP*  LON/LAT INDEX OF EACH SEA POINT.
C
      COMMON /MAP/ IXLG(NIBLO,NBLO), KXLT(NIBLO,NBLO), NX, NY, IPER,
     1             IRGG, AMOWEP, AMOSOP, AMOEAP, AMONOP, XDELLA, XDELLO,
     2             ZDELLO(NGY)
