C*    *COMMON* *STATUS* - TIME STATUS OF INTEGRATION, WIND INPUT,
C                         OUTPUT OF RESULTS, MODEL OPTIONS,
C                         AND ALTIMETER DATA ASSIMILATION WINDOW.
C
      CHARACTER*  2 MARSTYPE
      CHARACTER*  2 YCLASS
      CHARACTER*  4 YEXPVER
      CHARACTER* 10 CDATEA, CDATEE, CDATEF, CDTPRO, CDTRES, CDATER,
     &              CDATES, CDTINTT, CDTINTS, CDTSPT, CDTSPS
      CHARACTER*256 CFDBSF, CFDB2DSP
      INTEGER       MFDBSF, MFDB2DSP
C
      COMMON /STATUS/ IDELPRO, IDELT, IDELWI, IDELWO, IDELALT,
     1                IREST, IDELRES, IDELINT, IDELINS,
     2                IDELSPT, IDELSPS,
     3                ICASE, ISHALLO, IREFRA, IASSI,
     4                NTASKS, NSIZE, ISIGHUP, ISIGINT, NENSFNB, NTOTENS,
     5                CDATEA, CDATEE, CDATEF, CDTPRO, CDTRES, CDATER,
     6                CDATES, CDTINTT, CDTINTS, CDTSPT, CDTSPS,
     7                MARSTYPE, YCLASS, YEXPVER, CFDBSF, CFDB2DSP,
     8                MFDBSF, MFDB2DSP
