C*    *COMMON* *SHALLOW*   SHALLOW WATER TABLES.
C
      PARAMETER (NDEPTH = 52)
C
      COMMON /SHALLOW/ DEPTH(NIBLO, NBLO), DEPTHA, DEPTHD,
     1                 TCGOND(NDEPTH,NFRE), TFAK(NDEPTH,NFRE),
     2                 TSIHKD(NDEPTH,NFRE), INDEP(NIBLO)
