C*    *COMMON* *TEXT* - FILE NAME INFORMATION.
C
      LOGICAL   LRESTARTED
      INTEGER   ICPLEN
      CHARACTER USERID*3, RUNID*3, PATH*60, CPATH*80, CWI*87
      COMMON /TEXT/ ICPLEN, LRESTARTED, 
     1              USERID, RUNID, PATH, CPATH, CWI
