C*    *COMMON* *TABLE* - TABLE FOR TOTAL STRESS AND HIGH FREQ STRESS.
C
      PARAMETER (ITAUMAX=100, JUMAX=100, IUSTAR=100, IALPHA=100,
     1           JPLEVT = 1)
C
      COMMON /TABLE/ TAUT(0:ITAUMAX,0:JUMAX,JPLEVT), DELTAUW, DELU,
     1               TAUHFT(0:IUSTAR,0:IALPHA), DELUST, DELALP
