C*    *COMMON*  *WIND* - VARIABLES USED FOR WIND COMPUTATIONS.
C
      CHARACTER*12 CDA, CDAWIFL, CDATEWO, CDATEFL
      CHARACTER*12 CDTNEXT
      REAL,DIMENSION(NIBLO,NBLO) :: USNEXT,DSNEXT 
C
      COMMON/ WIND/ USNEXT,DSNEXT, 
     1              CDA, CDATEWO, CDAWIFL, CDATEFL, IIG, CDTNEXT
