SUBROUTINE GETODBRALT(IREAD, NIJALTP1, NOBS, NSATOBS)

!--------------------------------------------------------------------

!**** *GETODBRALT* - READS ALTIMETER DATA FROM ODB
!                    AND LOADS THEM IN ALTDATA and IJALT on PE IREAD.

!-----------------------------------------------------------------------

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      USE YOWALTAS , ONLY : NUMALT   ,NIJALT   ,NALTDT   ,   &
     &            IJALT    , NOBSPE  , ALTDATA ,IBUFRSAT ,   &
     &            ALTUNDATA, LODBRALT, CSATNAME
      USE YOWMPP   , ONLY : IRANK    ,NPROC    ,KTAG
      USE YOWSTAT  , ONLY : CDTPRO   ,IDELALT
      USE YOWTEST  , ONLY : IU06

      USE MPL_MODULE

#ifdef WITH_ODB
      USE DBASE_VIEW_MOD, ONLY: DBASE_VIEW
      USE YOWODB   , ONLY : WAM_YDODB
#endif

      USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

! ----------------------------------------------------------------------
IMPLICIT NONE

#include "abort1.intfb.h"
#include "incdate.intfb.h"


INTEGER(KIND=JWIM), INTENT(IN) :: IREAD      ! target processor 
INTEGER(KIND=JWIM), INTENT(IN) :: NIJALTP1   ! second dimension of IJALT

INTEGER(KIND=JWIM), INTENT(OUT):: NOBS       ! total number of altimeter observations acquired.
INTEGER(KIND=JWIM), INTENT(OUT) :: NSATOBS(NUMALT) ! NUMBER OF OBS. FROM EACH SAT.


INTEGER(KIND=JWIM) :: K, IOBS, JOBS, ITAG, NOBSDUM
INTEGER(KIND=JWIM) :: IOBS_S, KFROM, IOBS_EXTRA
INTEGER(KIND=JWIM) :: IR, IP, IK
INTEGER(KIND=JWIM) :: IZCOMLEN, ICOUNT
INTEGER(KIND=JWIM),ALLOCATABLE,DIMENSION(:,:) :: ITEMP

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

REAL(KIND=JWRB),ALLOCATABLE :: ZCOMBUFROD(:)
REAL(KIND=JWRB),ALLOCATABLE,DIMENSION(:,:) :: ZTEMP

#ifdef WITH_ODB
!     ODB-RELATED VARIABLES
TYPE(DBASE_VIEW)   :: ROBSU 
INTEGER(KIND=JWIM) :: IOBTYP, ISATID, ICDTYPE
INTEGER(KIND=JWIM) :: NRALT
INTEGER(KIND=JWIM) :: ISAT
INTEGER(KIND=JWIM) :: IEVENT2
INTEGER(KIND=JWIM) :: KTSLOT
INTEGER(KIND=JWIM) :: KPOOLNO
INTEGER(KIND=JWIM) :: IDATE, ITIME
INTEGER(KIND=JWIM) :: IRET
INTEGER(KIND=JWIM) :: ILIST(32),IRSTA(4),IDSTA(4)
INTEGER(KIND=JWIM) :: ISEND(1)

CHARACTER(LEN=14) :: CBEGINDT, CENDDT, COBSDT

LOGICAL, ALLOCATABLE, DIMENSION(:) :: LACCEPT
REAL(KIND=JWRU), POINTER :: ZODB_DATE(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_TIME(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_VARNO(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_OBSVALUE(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_DATUM_STATUS(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_REPORT_STATUS(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_DATUM_EVENT2(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_GP_NUMBER(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_SATELLITE_IDENTIFIER(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_OBSTYPE(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_CODETYPE(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_OBS_ERROR(:) => NULL()
REAL(KIND=JWRU), POINTER :: ZODB_BIASCORR(:) => NULL()
#endif

!     -------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GETODBRALT',0,ZHOOK_HANDLE)


NOBS=0
NSATOBS(:) = 0

#ifdef WITH_ODB
NRALT = 12    ! RADAR ALTIMETER TYPE

IF (LODBRALT) THEN
  !*        GET RALT OBSERVATIONS FROM ODB
  WRITE(IU06,*) '   GETODBRALT : ALTIMETER DATA ARE OBTAINED VIA ODB'
  IRET = WAM_YDODB%SELECT('ralt_wam',  ROBSU)

  ZODB_DATE => ROBSU%GET_COLUMN_PTR('date@hdr')
  ZODB_TIME => ROBSU%GET_COLUMN_PTR('time@hdr')
  ZODB_VARNO => ROBSU%GET_COLUMN_PTR('varno@body')
  ZODB_SATELLITE_IDENTIFIER => ROBSU%GET_COLUMN_PTR('satellite_identifier@sat')
  ZODB_BIASCORR => ROBSU%GET_COLUMN_PTR('biascorr@body')
  ZODB_OBS_ERROR => ROBSU%GET_COLUMN_PTR('obs_error@errstat')
  ZODB_OBSVALUE => ROBSU%GET_COLUMN_PTR('obsvalue@body')
  ZODB_DATUM_STATUS => ROBSU%GET_COLUMN_PTR('datum_status@body')
  ZODB_REPORT_STATUS => ROBSU%GET_COLUMN_PTR('report_status@hdr')
  ZODB_DATUM_EVENT2 => ROBSU%GET_COLUMN_PTR('datum_event2@body')
  ZODB_OBSTYPE => ROBSU%GET_COLUMN_PTR('obstype@hdr')
  ZODB_CODETYPE => ROBSU%GET_COLUMN_PTR('codetype@hdr')
  ZODB_GP_NUMBER => ROBSU%GET_COLUMN_PTR('gp_number@hdr')

  IF (ROBSU%NROWS > 0) THEN
    CBEGINDT = CDTPRO
    IF (IDELALT <= 10800) THEN
      ! for any IDELALT <= 3 hours, all data in [CDTPRO - IDELALT sec., CDTPRO] will be used
      CALL INCDATE (CBEGINDT,-IDELALT)
    ELSE
      ! for any IDELALT > 3 hours, all data centeted on CDTPRO will be used (+- IDELALT/2) 
      CALL INCDATE (CBEGINDT,-IDELALT/2)
    ENDIF
    CENDDT = CBEGINDT
    CALL INCDATE (CENDDT,IDELALT)

    IF (ALLOCATED(LACCEPT)) DEALLOCATE (LACCEPT)
    ALLOCATE(LACCEPT(ROBSU%NROWS))
    LACCEPT(:)=.TRUE.
    DO JOBS = 1, ROBSU%NROWS
      IDATE=NINT(ZODB_DATE(JOBS))
      ITIME=NINT(ZODB_TIME(JOBS))
      IF (IDATE >= 0 .AND. IDATE <= 99991231 .AND.                       &
     &    ITIME >= 0 .AND. ITIME <= 999999         ) THEN
        WRITE(COBSDT,'(I8.8,I6.6)') IDATE, ITIME
        IOBTYP=NINT(ZODB_OBSTYPE(JOBS))
        ICDTYPE=NINT(ZODB_CODETYPE(JOBS))
        ISATID=NINT(ZODB_SATELLITE_IDENTIFIER(JOBS))
      ! Select wave height Var.Num.=220 ONLY !!!!
      ! If $ralt_swh = 220 in file odb/ddl/varno.h changes, you need to change it here
        LACCEPT(JOBS)=NINT(ZODB_VARNO(JOBS)) == 220                       &
     &                .AND. LGE(COBSDT,CBEGINDT) .AND. LLE(COBSDT,CENDDT)
      ELSE
        LACCEPT(JOBS)=.FALSE.
      ENDIF

      IF (LACCEPT(JOBS)) THEN
        IF (IOBTYP == NRALT) THEN
          LACCEPT(JOBS)=.FALSE.
          DO ISAT=1, NUMALT
            IF (ISATID == IBUFRSAT(ISAT)) THEN 
              NSATOBS(ISAT) = NSATOBS(ISAT) + 1
              LACCEPT(JOBS)=.TRUE.
              EXIT
            ENDIF
          ENDDO
          IF (.NOT.LACCEPT(JOBS)) THEn
            WRITE(IU06,*)'WARNING IN GETODBRALT: UNKNOWN RALT CODE TYPE ', ICDTYPE
            WRITE(IU06,*)'FOR SATELLITE ID : ', ISATID
          ENDIF
        ELSE
          LACCEPT(JOBS)=.FALSE.
          WRITE(IU06,*)'WARNING IN GETODBRALT: UNKNOWN OBS. TYPE ', IOBTYP
        ENDIF
      ENDIF
    ENDDO
  ENDIF

  NOBS = 0
  DO ISAT=1, NUMALT
    NOBS = NOBS + NSATOBS(ISAT)
    IF (NSATOBS(ISAT) > 0 ) WRITE(IU06,*) &
     &   '    '//TRIM(CSATNAME(ISAT))//' HS OBS. FOUND: ', NSATOBS(ISAT)
  ENDDO

  IF (NOBS > 0) THEN
    ALLOCATE(IJALT(NOBS,NIJALTP1))
    ! THE WIND SPEED IS NOT READ IN. IT WILL BE KEPT PASSIVE
    ! ALL THE WAY TO WAM2ODB, WHERE MODEL INFORMATION WILL BE ADDED
    IJALT(1:NOBS,4:NIJALTP1) = 0
    ALLOCATE(ALTDATA(NOBS,NALTDT))
!!!!? ALTUNDATA not yet used !!!!!!!!!!
  ENDIF

  IOBS = 0
  DO JOBS = 1, ROBSU%NROWS
    IF (LACCEPT(JOBS)) THEN
      IOBS = IOBS+1
      IOBTYP=NINT(ZODB_OBSTYPE(JOBS))
      ICDTYPE=NINT(ZODB_CODETYPE(JOBS))
      IJALT(IOBS,1)=NINT(ZODB_GP_NUMBER(JOBS))
      IJALT(IOBS,2)=NINT(ZODB_SATELLITE_IDENTIFIER(JOBS))


!     report_status
      IRSTA(1) = IBITS(NINT(ZODB_REPORT_STATUS(JOBS)),0,1)
      IRSTA(2) = IBITS(NINT(ZODB_REPORT_STATUS(JOBS)),1,1)
      IRSTA(3) = IBITS(NINT(ZODB_REPORT_STATUS(JOBS)),2,1)
      IRSTA(4) = IBITS(NINT(ZODB_REPORT_STATUS(JOBS)),3,1)

!     datum_status
      IDSTA(1) = IBITS(NINT(ZODB_DATUM_STATUS(JOBS)),0,1)
      IDSTA(2) = IBITS(NINT(ZODB_DATUM_STATUS(JOBS)),1,1)
      IDSTA(3) = IBITS(NINT(ZODB_DATUM_STATUS(JOBS)),2,1)
      IDSTA(4) = IBITS(NINT(ZODB_DATUM_STATUS(JOBS)),3,1)

!     datum_event2
      IEVENT2=NINT(ZODB_DATUM_EVENT2(JOBS))

!     REBUILD IJALT(IOBS,3)


      IF (IRSTA(1) == 1) THEN
        IF (IDSTA(1) == 1) THEN
          ! ACTIVE
          IJALT(IOBS,3)=1
        ELSEIF (IDSTA(2) == 1) THEN
          ! PASSIVE
          IJALT(IOBS,3)=0
        ELSE IF (IDSTA(4) == 1) THEN
          ! BLACKLISTED
          IJALT(IOBS,3)=0
        ELSE IF (IDSTA(3) == 1) THEN
          ! REJECTED
          IJALT(IOBS,3)=MIN(IEVENT2,-1)
        ELSE
          ! REJECTED WITH STATUS -1
          IJALT(IOBS,3)=-1
        ENDIF

      ELSE IF (IRSTA(2) == 1) THEN
        ! PASSIVE
        IJALT(IOBS,3)=0
      ELSE IF (IRSTA(4) == 1) THEN
        ! BLACKLISTED
        IJALT(IOBS,3)=0
      ELSE
        ! REJECTED
        IJALT(IOBS,3)=-1
      ENDIF

      ALTDATA(IOBS,1)=ZODB_OBSVALUE(JOBS)

      ALTDATA(IOBS,2)=ZODB_OBS_ERROR(JOBS)

      IF (IJALT(IOBS,3) /= -1) THEN
        ALTDATA(IOBS,3)=ALTDATA(IOBS,1)-ZODB_BIASCORR(JOBS)
      ELSE
        ALTDATA(IOBS,3)=ALTDATA(IOBS,1)
      ENDIF
    ENDIF
  ENDDO

  IF (ALLOCATED(ROBSU%DATA)) IRET = WAM_YDODB%PUT(ROBSU)

  IF (ASSOCIATED(ZODB_DATE)) NULLIFY(ZODB_DATE)
  IF (ASSOCIATED(ZODB_TIME)) NULLIFY(ZODB_TIME)
  IF (ASSOCIATED(ZODB_OBSTYPE)) NULLIFY(ZODB_OBSTYPE)
  IF (ASSOCIATED(ZODB_CODETYPE)) NULLIFY(ZODB_CODETYPE)
  IF (ASSOCIATED(ZODB_GP_NUMBER)) NULLIFY(ZODB_GP_NUMBER)
  IF (ASSOCIATED(ZODB_SATELLITE_IDENTIFIER)) NULLIFY(ZODB_SATELLITE_IDENTIFIER)
  IF (ASSOCIATED(ZODB_REPORT_STATUS)) NULLIFY(ZODB_REPORT_STATUS)
  IF (ASSOCIATED(ZODB_DATUM_STATUS)) NULLIFY(ZODB_DATUM_STATUS)
  IF (ASSOCIATED(ZODB_DATUM_EVENT2)) NULLIFY(ZODB_DATUM_EVENT2)
  IF (ASSOCIATED(ZODB_VARNO)) NULLIFY(ZODB_VARNO)
  IF (ASSOCIATED(ZODB_OBSVALUE)) NULLIFY(ZODB_OBSVALUE)
  IF (ASSOCIATED(ZODB_OBS_ERROR)) NULLIFY(ZODB_OBS_ERROR)
  IF (ASSOCIATED(ZODB_BIASCORR)) NULLIFY(ZODB_BIASCORR)

  IF (NPROC > 1) THEN
    WRITE(IU06,*) ' GETODBRALT: IRANK IS:', IRANK

    !! Lets gather all data at PE IREAD before distributing them later among other PE's

    ! Each PE will send the data (in any) it has to the master PE (IREAD)

    ! Send number of observations and receive them by IREAD:
    ! this is in case the data feed from ODB was done in parallel
    CALL GSTATS(618,0)
    IF (IRANK /= IREAD) THEN
      CALL MPL_SEND(IOBS,KDEST=IREAD,KTAG=KTAG, &
     &              CDSTRING='GETODBRALT 0:')
    ELSE
      NOBSPE(IREAD) = IOBS
      IOBS_EXTRA = 0
      DO IR=1, NPROC-1
        CALL MPL_RECV(IOBS_S,KFROM=KFROM,KTAG=KTAG,CDSTRING='GETODBRALT 0:') 
        NOBSPE(KFROM) = IOBS_S 
        IOBS_EXTRA = IOBS_EXTRA + IOBS_S
      ENDDO

      WRITE(IU06,*) ' GETODBRALT: NUMBER OF OBSERVATIONS COLLECTED.'
      IF (IOBS_EXTRA > 0 ) THEN
        DO IR=1, NPROC
          WRITE(IU06,*) ' GETODBRALT: IR, NOBSPE(IR) = ',IR, NOBSPE(IR)
        ENDDO
      ELSE
          WRITE(IU06,*) ' GETODBRALT: IREAD, NOBSPE(IREAD) = ',IREAD, NOBSPE(IREAD)
      ENDIF
      WRITE(IU06,*) '' 
    ENDIF
    CALL GSTATS(618,1)

    CALL MPL_BARRIER(CDSTRING='GETODBRALT 0:')
    KTAG=KTAG+1

    ! Send actual data (IJALT and ALTDATA) and receive them by IREAD
    IF (IRANK /= IREAD .AND. IOBS /= 0) THEN
      IZCOMLEN = IOBS*NALTDT + IOBS*NIJALTP1
      ALLOCATE(ZCOMBUFROD(IZCOMLEN))

      ICOUNT = 0
      DO K=1, NALTDT
        DO JOBS = 1, IOBS
          ICOUNT = ICOUNT + 1
          ZCOMBUFROD(ICOUNT) = ALTDATA(JOBS,K)
        ENDDO
      ENDDO
      DO K=1, NIJALTP1
        DO JOBS = 1, IOBS
          ICOUNT = ICOUNT + 1
          ZCOMBUFROD(ICOUNT) = REAL(IJALT(JOBS,K),JWRB)
        ENDDO
      ENDDO
      DEALLOCATE(ALTDATA)
      DEALLOCATE(IJALT)

      CALL GSTATS(618,0)
      CALL MPL_SEND(ZCOMBUFROD,KDEST=IREAD,KTAG=KTAG+IRANK, CDSTRING='GETODBRALT 1:')
      CALL GSTATS(618,1)
      DEALLOCATE(ZCOMBUFROD)

    ELSEIF (IRANK == IREAD) THEN

      ! On PE IREAD
      ! Allocate the arrays for all data and move any data on this PE to the new arrays

      IF (IOBS /= 0) THEN
        IF (ALLOCATED(ZTEMP)) DEALLOCATE(ZTEMP)
        ALLOCATE(ZTEMP(IOBS,NALTDT))
        DO K=1, NALTDT
          DO JOBS = 1, IOBS
            ZTEMP(JOBS,K) = ALTDATA(JOBS,K)
          ENDDO
        ENDDO
        IF (ALLOCATED(ITEMP)) DEALLOCATE(ITEMP)
        ALLOCATE(ITEMP(IOBS,NIJALTP1))
        DO K=1, NIJALTP1
          DO JOBS = 1, IOBS
            ITEMP(JOBS,K) = IJALT(JOBS,K)
          ENDDO
        ENDDO
      ENDIF

      NOBS = SUM(NOBSPE)
      IF (ALLOCATED(ALTDATA)) DEALLOCATE(ALTDATA)
      ALLOCATE(ALTDATA(NOBS,NALTDT))
      IF (ALLOCATED(IJALT)) DEALLOCATE(IJALT)
      ALLOCATE(IJALT(NOBS,NIJALTP1))

      IF (IOBS /= 0) THEN
        DO K=1, NALTDT
          DO JOBS = 1, IOBS
            ALTDATA(JOBS,K) = ZTEMP(JOBS,K)
          ENDDO
        ENDDO
        DEALLOCATE(ZTEMP)
        DO K=1, NIJALTP1
          DO JOBS = 1, IOBS
            IJALT(JOBS,K) = ITEMP(JOBS,K)
          ENDDO
        ENDDO
        DEALLOCATE(ITEMP)
      ENDIF

      !   Receive actual data (IJALT and ALTDATA) on IREAD

      CALL GSTATS(618,0)
      DO IR=1, NPROC
        IF (IR /= IREAD .AND. NOBSPE(IR) /= 0) THEN
          IZCOMLEN = NOBSPE(IR)*NALTDT + NOBSPE(IR)*NIJALTP1
          ALLOCATE(ZCOMBUFROD(IZCOMLEN))
          CALL MPL_RECV(ZCOMBUFROD,KSOURCE=IR,KTAG=KTAG+IR, CDSTRING='GETODBRALT 1:') 
          NOBSDUM = IOBS + 1
          IOBS = IOBS + NOBSPE(IR)
          ICOUNT = 0
          DO K=1, NALTDT
            DO JOBS = NOBSDUM, IOBS
              ICOUNT = ICOUNT + 1
              ALTDATA(JOBS,K) = ZCOMBUFROD(ICOUNT)
            ENDDO
          ENDDO
          DO K=1, NIJALTP1
            DO JOBS = NOBSDUM, IOBS
              ICOUNT = ICOUNT + 1
              IJALT(JOBS,K) = NINT(ZCOMBUFROD(ICOUNT))
            ENDDO
          ENDDO

          DEALLOCATE(ZCOMBUFROD)
        ENDIF
      ENDDO
      CALL GSTATS(618,1)
    ENDIF

    CALL MPL_BARRIER(CDSTRING='GETODBRALT 1:')
    KTAG=KTAG+NPROC

    IF (NOBS /= IOBS) THEN
      WRITE(IU06,*) ' GETODBRALT: COMMUNICATION ERROR - MISMATCH IN NUMBER OF OBS.'
      WRITE(IU06,*) '          NUMBER REPORTED: ', NOBS, '  NUMBER RECEIVED: ', IOBS
      WRITE(IU06,*) '          EXECUTION CONTINUES --- OR SHOULD WE FAIL!!!!!!!'
    ENDIF
    CALL FLUSH(IU06)

  ENDIF  ! endif NPROC > 1

ENDIF

#endif
IF (LHOOK) CALL DR_HOOK('GETODBRALT',1,ZHOOK_HANDLE)

END SUBROUTINE GETODBRALT
