SUBROUTINE WAM_ODB_CLOSE
#ifdef WITH_ODB
    USE YOWODB, ONLY : WAM_YDODB
    USE PARKIND_WAVE, ONLY : JWIM

    IMPLICIT NONE

    INTEGER(KIND=JWIM) :: IRET

    IRET = WAM_YDODB%CLOSE(SAVE=.TRUE.)
#endif
END SUBROUTINE
