SUBROUTINE WAM_ODB_OPEN
#ifdef WITH_ODB
    USE YOWODB, ONLY : WAM_YDODB
    USE DBASE_FACTORY_MOD
    USE PARKIND_WAVE, ONLY : JWIM

    IMPLICIT NONE

    INTEGER(KIND=JWIM)  :: IRET
    TYPE(DBASE_FACTORY) :: DB_FACTORY

    CALL DB_FACTORY%INIT("odb1")
    WAM_YDODB => DB_FACTORY%CREATE_DBASE()

    IRET = WAM_YDODB%OPEN("ECMA","w")
#endif
END SUBROUTINE
