#if defined MODEL_COUPLING_ATM_WAV || defined MODEL_COUPLING_OCN_WAV
#else
MODULE COUPLING_VAR
  USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
  IMPLICIT NONE
  INTEGER(KIND=JWIM) :: WAV_COMM_WORLD 
  REAL(KIND=JWRU) :: WAV_PresTime, CouplingTime_ATM_WAV, ATM_EXCHANGE, TEST_DIV
END MODULE COUPLING_VAR
#endif
