      MODULE YOWCOUT

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *COUT*  OUTPUT POINTS INDICES AND FLAGS.

      INTEGER(KIND=JWIM), PARAMETER :: NTRAIN=3 
      INTEGER(KIND=JWIM), PARAMETER :: JPPFLAG=69+3*NTRAIN+5 !!!! change also in scripts: wave_setgflag
      INTEGER(KIND=JWIM), PARAMETER :: NREAL=11 
      INTEGER(KIND=JWIM), PARAMETER :: NIPRMINFO=5
      INTEGER(KIND=JWIM), PARAMETER :: NINFOBOUT=3

      CHARACTER(LEN=14), ALLOCATABLE :: COUTT(:)
      CHARACTER(LEN=14) :: COUTLST 
      CHARACTER(LEN=14), ALLOCATABLE :: COUTS(:) 
      CHARACTER(LEN=14), ALLOCATABLE :: CASS(:) 

      CHARACTER(LEN=33) :: COUTNAME(JPPFLAG)

#ifdef MODEL_COUPLING_ATM_WAV
      LOGICAL COUPLFLAG(JPPFLAG) 
!        COUPLFLAG is for the statistics that we should compute 
!        and that are related to the coupling.
#endif
      LOGICAL :: FFLAG(JPPFLAG) 
      LOGICAL :: FFLAG20 
      LOGICAL :: PFLAG(JPPFLAG) 
      LOGICAL :: PFLAG20 
      LOGICAL :: GFLAG(JPPFLAG) 
      LOGICAL :: GFLAG20 
      LOGICAL :: NFLAG(JPPFLAG) 
      LOGICAL :: NFLAGALL 
      LOGICAL :: LLOUTERS
      LOGICAL :: UFLAG(JPPFLAG) 
      LOGICAL :: LFDB 
      LOGICAL :: LOUTINT 
      LOGICAL :: LWFLUXOUT
      LOGICAL :: LSECONDORDER
      LOGICAL :: LRSTST0
      LOGICAL :: LWAMANOUT
      LOGICAL :: LRSTPARALR
      LOGICAL :: LRSTPARALW
      LOGICAL :: LRSTINFDAT
      LOGICAL :: LLPARTITION
      LOGICAL :: LWAM_USE_IO_SERV

      INTEGER(KIND=JWIM) :: NWRTOUTWAM=1
      INTEGER(KIND=JWIM) :: NIPRMOUT 
      INTEGER(KIND=JWIM) :: NGOUT
      INTEGER(KIND=JWIM), ALLOCATABLE :: IGAR(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJAR(:)
      INTEGER(KIND=JWIM) :: NOUTT
      INTEGER(KIND=JWIM) :: NOUTS
      INTEGER(KIND=JWIM) :: NASS
      INTEGER(KIND=JWIM) :: IRWDIR,IRCD,IRU10,IRHS,IRTP,IRT1,IRPHIOC,IRTAUOC
      INTEGER(KIND=JWIM) :: IRHSWS, IRT1WS, IRBATHY
      INTEGER(KIND=JWIM) :: IRALTHS,IRALTHSC,IRALTRC
      INTEGER(KIND=JWIM) :: IFRSTPARTI
      INTEGER(KIND=JWIM) :: IPFGTBL(JPPFLAG+1)
      INTEGER(KIND=JWIM), PARAMETER :: KDEL=1
      INTEGER(KIND=JWIM), PARAMETER :: MDEL=1
      INTEGER(KIND=JWIM) :: IPRMINFO(JPPFLAG,NIPRMINFO)
      INTEGER(KIND=JWIM) :: ITOBOUT(JPPFLAG)
      INTEGER(KIND=JWIM), ALLOCATABLE, DIMENSION(:,:) :: INFOBOUT

      REAL(KIND=JWRB), ALLOCATABLE, DIMENSION(:,:) :: BOUT

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *NTRAIN*    INTEGER   MAXIMUM NUMBER OF SWELL TRAINS.
!      *NREAL*     INTEGER   NUMBER OF REAL FIELDS IN RESTART FILE
!      *NIPRMINFO* INTEGER   NUMBER OF AUXILLIARY INFORMATION ITEMS ON OUTPUT INTEGRATED PARAMETERS
!      *NINFOBOUT* INTEGER   NUMBER OF AUXILLIARY INFORMATION NEEDED TO ENCODE IN GRIB THE INTEGRATED PARAMETERS
!      *COUTT*     CHAR*14   OUTPUT TIMES.
!      *COUTLST*   CHAR*14   LAST OUTPUT TIME.
!      *COUTS*     CHAR*14   OUTPUT TIMES FOR THE SPECTRA.
!      *CASS*      CHAR*14   ASSIMILATION TIMES.
!      *COUTNAME   CHARACTER NAME OF THE OUTPUT VARIABLES
!      *FFLAG*     LOGICAL   FILE  OUTPUT FLAG FOR EACH OUTPUT TYPE.
!      *FFLAG20*   LOGICAL   .TRUE. IF OUTPUT IS WRITTEN TO UNIT IU20.
!      *PFLAG*     LOGICAL   PRINT OUTPUT FLAG FOR EACH OUTPUT TYPE.
!      *PFLAG20*   LOGICAL   .TRUE. IF PRINT OUTPUT OF FIELDS.
!      *GFLAG*     LOGICAL   GRIB  OUTPUT FLAG FOR EACH OUTPUT TYPE.
!      *GFLAG20*   LOGICAL   .TRUE. IF OUTPUT IS GRIBBED TO UNIT IU30.
!      *NFLAG*     LOGICAL   NORM OUTPUT FLAG FOR EACH OUTPUT TYPE.
!      *NFLAGALL*  LOGICAL   .TRUE. IF NORM OUTPUT IS REQUESTED.
!      *LLOUTERS*  LOGICAL   .TRUE. IF OUTERS IS CALLED AT ALL.
!      *UFLAG*     LOGICAL   FLAG WHETHER OUTPUT GRID FIELD IS USED
!                            IN THE ASSIMILATION SCHEME
!      *LFDB*      LOGICAL   .TRUE. IF OUTPUT IS SENT TO FDB.
!      *LOUTINT*   LOGICAL   .TRUE. IF OUTINT WAS CALLED.
!      *NGOUT*     INTEGER   NUMBER OF OUTPUT POINTS.
!      *IGAR*      INTEGER   BLOCK NUMBER OF OUTPUT POINTS.
!      *IJAR*      INTEGER   GRIDPOINT NUMBER OF OUTPUT POINT.
!      *NOUTT*     INTEGER   NUMBER OF OUTPUT TIMES.
!      *NOUTS*     INTEGER   NUMBER OF OUTPUT TIMES FOR THE SPECTRA.
!      *NASS*      INTEGER   NUMBER OF ASSIMILATION TIMES.
!      *IRWDIR*    INTEGER   INDEX IN IPFGTBL OF WIND DIRECTION
!      *IRCD*      INTEGER   INDEX IN IPFGTBL OF CD
!      *IRU10*     INTEGER   INDEX IN IPFGTBL OF U10 
!      *IRHS*      INTEGER   INDEX IN IPFGTBL OF HS
!      *IRTP*      INTEGER   INDEX IN IPFGTBL OF TP 
!      *IRT1*      INTEGER   INDEX IN IPFGTBL OF T1 
!      *IRPHIOC*   INTEGER   INDEX IN IPFGTBL OF PHIOC
!      *IRTAUOC*   INTEGER   INDEX IN IPFGTBL OF TAUOC
!      *IRHSWS*    INTEGER   INDEX IN IPFGTBL OF HS WINDSEA 
!      *IRT1WS*    INTEGER   INDEX IN IPFGTBL OF T1 WINDSEA 
!      *IRBATHY*   INTEGER   INDEX IN IPFGTBL OF WATER DEPTH
!      *IRALTHS*   INTEGER   INDEX IN IPFGTBL OF ALTIMETER HS
!      *IRALTHSC*  INTEGER   INDEX IN IPFGTBL OF ALTIMETER HS CORRECTED 
!      *IRALTRC*   INTEGER   INDEX IN IPFGTBL OF ALTIMETER RANGE CORRECTION 
!      *IFRSTPARTI*INTEGER   INDEX IN IPFGTBL OF THE FIRST PARTITONED PARAMETERS 
!      *KDEL*      INTEGER   NUMBER OF DIRECTIONS THAT WILL BE WRITTEN
!                            OUT/READ IN WHEN BINARY SPECTRA ARE PRODUCED
!      *MDEL*      INTEGER   NUMBER OF FREQUENCIES THAT WILL BE WRITTEN
!                            OUT/READ IN WHEN BINARY SPECTRA ARE PRODUCED
!      *LWFLUXOUT* LOGICAL   TRUE IF THE OCEAN FLUXES ARE OUTPUT PARAMETERS.
!      *LSECONDORDER*        TRUE IF SECOND ORDER CORRECTION IS COMPUTED
!                            FOR OUTPUT INTEGRATED PARAMETERS.
!      *LRSTST0    LOGICAL   TRUE IF GRIB HEADER HAVE TO BE RESET
!                            SUCH THAT THE FORECAST STEP POINTS TO
!                            THE START OF THE RUN.
!      *LWAMANOUT* LOGICAL   CONTROLS WHETHER FIELDS WILL BE WRITTEN AT 
!                            ANALYSIS TIME OR NOT. (USEFUL WHEN WAVE DATA
!                            ASSIMILATION IS DONE IN MORE THAN ONE TRAJECTORY.)
!      *LRSTPARALR*LOGICAL   TRUE WILL READ BINARY RESTART FILES IN PARALLEL (i.e. PER MPI TASK)
!      *LRSTPARALW*LOGICAL   TRUE WILL WRITE BINARY RESTART FILES IN PARALLEL (i.e. PER MPI TASK)
!      *LRSTINFDAT*LOGICAL   TRUE WILL WRITE AN ADDITIONAL wamfile WITH DATE/TIME INFO
!      *LLPARTITION*         TRUE IF ANY SWELL PARTITION PARAMETER IS TO BE OUPUT
!      *NWRTOUTWAM INTEGER   CONTROLS THE STRIDE WITH WHICH FDB OUTPUT PE's
!                            ARE SELECTED (BY DEFAULT = 1)
!      *NIPRMOUT* INTEGER    ACTUAL TOTAL NUMBER OF OUTPUT INTEGRATED PARAMETERS 
!      *IPRMINFO* INTEGER    AUXILIARY INFORMATION FOR OUTPUT OF INTEGRATED PARAMETERS
!                            IPRMINFO(:,1)  : GRIB TABLE NUMBER.
!                            IPRMINFO(:,2)  : GRIB PARAMETER IDENTIFIER.
!                            IPRMINFO(:,3)  : GRIB REFERENCE LEVEL IN FULL METER.
!                            IPRMINFO(:,4)  : 1 IF SEA ICE MASK IS IMPOSED ON OUTPUT FIELD.
!                            IPRMINFO(:,5)  : 1 IF TOO SHALLOW POINTS ARE SET TO MISSING.
!      *ITOBOUT*  INTEGER    GIVES THE INDEX IN BOUT OF THE INTEGRATED FIELDS THAT ARE ACTUALLY OUTPUT
!      *INFOBOUT*            AUXILIARY INFORMATION TO ENCODE INTEGRATED PARAMETERS IN GRIB
!                            INFOBOUT(:,1)  : GRIB TABLE NUMBER.
!                            INFOBOUT(:,2)  : GRIB PARAMETER IDENTIFIER.
!                            INFOBOUT(:,3)  : GRIB REFERENCE LEVEL IN FULL METER.
!      *BOUT*    REAL        CONTAINS THE LOCAL CONTRIBUTIONS OF INTEGRATED FIELDS THAT ARE ACTUALLY OUTPUT
!      *LWAM_USE_IO_SERV*   LOGICAL   CONTROLS WHETHER WAVE MODEL SHOULD USE IFS IO SERVER
! ----------------------------------------------------------------------
      END MODULE YOWCOUT
