      MODULE YOWCURG

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *CURGRD* - INPUT GRID CURRENT SPECFICATIONS.

      REAL(KIND_JWRB) :: DUCLO 
      REAL(KIND_JWRB) :: DUCLA 
      REAL(KIND_JWRB) :: UCLO 
      REAL(KIND_JWRB) :: UCLH 
      REAL(KIND_JWRB) :: UCLW 
      REAL(KIND_JWRB) :: UCLE 
      REAL(KIND_JWRB), ALLOCATABLE :: UCUR(:,:)
      REAL(KIND_JWRB), ALLOCATABLE :: VCUR(:,:)
      INTEGER(KIND=JWIM) :: KRCI 
      INTEGER(KIND=JWIM) :: KCCI 
      INTEGER(KIND=JWIM) :: IPCUR 

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *DUCLO*     REAL      STEPSIZE BETWEEN LONGITUDES IN DEG.
!      *DUCLA*     REAL      STEPSIZE BETWEEN LATITUDES  IN DEG.
!      *UCLO*      REAL      MOST SOUTHERN LATITUDE.
!      *UCLH*      REAL      MOST NORTHERN LATITUDE.
!      *UCLW*      REAL      LEFT MOST LONGITUDE.
!      *UCLE*      REAL      RIGHT MOST LONGITUDE.
!      *UCUR       REAL      U - GRIDDED COMPONENT OF CURRENT (M/S).
!      *VCUR       REAL      V - GRIDDED COMPONENT OF CURRENT (M/S).
!      *KCCI*      INTEGER   NUMBER OF COLUMNES IN CURRENT INPUT (USED).
!      *KRCI*      INTEGER   NUMBER OF ROWS     IN CURRENT INPUT (USED).
!      *IPCUR*     INTEGER   INDICATOR PERIODICAL(GLOBAL) GRID OR NOT
!                            0 = NON-PERIODICAL;  1 = PERIODICAL
! ----------------------------------------------------------------------
      END MODULE YOWCURG
