      MODULE YOWCOUP

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
      USE YOWNEMOP    , ONLY : NEMODP

      IMPLICIT NONE

#include "outwspec_io_serv.intfb.h"
#include "outint_io_serv.intfb.h"

      !*    ** *COUPL* - PARAMETERS FOR COUPLING.

      INTEGER(KIND=JWIM), PARAMETER :: JPLEVC=1
      LOGICAL :: LLCAPCHNK 
      LOGICAL :: LWCOU
      LOGICAL :: LWNEMOCOU=.FALSE.
      LOGICAL :: LWNEMOCOUSEND
      LOGICAL :: LWNEMOTAUOC
      LOGICAL :: LWNEMOCOUSTRN=.FALSE.
      LOGICAL :: LWNEMOCOURECV
      LOGICAL :: LWNEMOCOUCIC=.FALSE.
      LOGICAL :: LWNEMOCOUCIT=.FALSE.
      LOGICAL :: LWNEMOCOUCUR=.FALSE.
      LOGICAL :: LWNEMOCOUSTK=.FALSE.
      LOGICAL :: LWNEMOCOUDEBUG
      LOGICAL :: LWCOU2W
      LOGICAL :: LWFLUX
      LOGICAL :: LWVFLX_SNL
      LOGICAL :: LWCOUNORMS
      LOGICAL :: LLNORMIFS2WAM
      LOGICAL :: LLNORMWAM2IFS
      LOGICAL :: LLNORMWAMOUT
      LOGICAL :: LLNORMWAMOUT_GLOBAL
      LOGICAL :: LMASK_OUT_NOT_SET
      LOGICAL :: LMASK_TASK_STR
      INTEGER(KIND=JWIM) KCOUSTEP
      INTEGER(KIND=JWIM), ALLOCATABLE :: LFROMTASK(:), LTOTASK(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJFROMTASK(:), IJTOTASK(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: ISTFROMTASK(:), ISTTOTASK(:)
      INTEGER(KIND=JWIM) :: NFROMTASKS, NTOTASKS
      INTEGER(KIND=JWIM), ALLOCATABLE :: I_MASK_IN(:)
      INTEGER(KIND=JWIM) :: N_MASK_IN
      INTEGER(KIND=JWIM), ALLOCATABLE :: I_MASK_OUT(:), J_MASK_OUT(:)
      INTEGER(KIND=JWIM) :: N_MASK_OUT

      REAL(KIND=JWRB) :: BETAMAX
      REAL(KIND=JWRB) :: ZALP
      REAL(KIND=JWRB) :: ALPHA
      REAL(KIND=JWRB) :: TAUWSHELTER
      INTEGER(KIND=JWIM) :: ITSHELT
      REAL(KIND=JWRB) :: TAILFACTOR
      REAL(KIND=JWRB) :: TAILFACTOR_PM
      REAL(KIND=JWRB) :: XKAPPA
      REAL(KIND=JWRB) :: RNU
      REAL(KIND=JWRB) :: RNUM
      REAL(KIND=JWRB) :: XNLEV(JPLEVC)

      INTEGER(KIND=JWIM), PARAMETER :: JTOT_TAUHF=19  ! must be odd !!! 
      REAL(KIND=JWRB) :: WTAUHF(JTOT_TAUHF)
      REAL(KIND=JWRB) :: X0TAUHF

      REAL(KIND=NEMODP), ALLOCATABLE :: NSWH(:), NMWP(:)
      REAL(KIND=NEMODP), ALLOCATABLE :: NPHIEPS(:), NTAUOC(:)
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOSTRN(:) 
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOUSTOKES(:) 
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOVSTOKES(:) 

      INTEGER(KIND=JWIM) :: NEMONTAU
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOTAUX(:), NEMOTAUY(:)
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMONEW10(:), NEMOPHIF(:)

      INTEGER(KIND=JWIM) :: NEMOINIDATE
      INTEGER(KIND=JWIM) :: NEMOINITIME
      INTEGER(KIND=JWIM) :: NEMOITINI
      INTEGER(KIND=JWIM) :: NEMOITEND
      REAL(KIND=NEMODP)  :: NEMOTSTEP
      INTEGER(KIND=JWIM) :: NEMOFRCO
      INTEGER(KIND=JWIM) :: NEMONSTEP
      INTEGER(KIND=JWIM) :: NEMOCSTEP
      INTEGER(KIND=JWIM) :: NEMOWSTEP

      INTEGER(KIND=JWIM) :: IFSNSTEP
      REAL(KIND=JWRB)    :: IFSTSTEP
      LOGICAL :: LIFS_IO_SERV_ENABLED
      PROCEDURE(OUTWSPEC_IO_SERV), POINTER :: OUTWSPEC_IO_SERV_HANDLER=> NULL()
      PROCEDURE(OUTINT_IO_SERV)  , POINTER :: OUTINT_IO_SERV_HANDLER  => NULL()

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *JPLEVC*    INTEGER   NUMBER OF REFERENCE LEVEL FOR WINDS.
!      *LWCOU*     LOGICAL   CONTROLS COUPLING WITH ATMOSPHERIC MODEL
!      *LWNEMOCOUSEND* L     SENDS DATA TO THE NEMO MODEL.
!      *LWNEMOCOUSTK LOGI.   SEND SURFACE STOKES DRIFT TO NEMO
!      *LWNEMOCOUSTRN LOGI.  SEND ICE WAVE STRAIN TO NEMO
!      *LWNEMOCOURECV* L     RECV DATA FROM THE NEMO MODEL.
!      *LWNEMOCOU* LOGICAL   CONTROLS COUPLING WITH NEMO OCEAN MODEL
!      *LWNEMOCOUDEBUG* LO   EXTRA NETCDF DEBUGGING OUTPUT FOR NEMO COUPLING
!      *LWNEMOTAUOC* LO      USE TAUOC OR FULL TAU FOR SENDING TO NEMO
!      *LWNEMOCOUCIC LOGI.   USE THE ICE CONCENTRATION FROM NEMO for open ocean points as determined by the lake cover (see micep)
!      *LWNEMOCOUCIT LOGI.   USE THE ICE THICKNESS FROM NEMO (see LWNEMOCOUCIC)
!      *LWNEMOCOUCUR LOGI.   USE THE OCEAN CURRENTS FROM NEMO for open ocean points as determined by the lake cover (see getcurr)
!      *LWCOU2W*   LOGICAL   CONTROLS 1-WAY OR 2-WAY COUPLING
!      *LWFLUX*    LOGICAL   IF TRUE FLUXES FOR OCEAN MODEL ARE PRODUCED
!                            FOR THE IFS.
!      *LWVFLX_SNL LOGICAL   IF TRUE FLUXES FOR OCEAN MODEL ARE PRODUCED
!                            WITh THE NONLINEAR SOURCE TERM CONTRIBUTION
!      *LWCOUNORMS*LOGICAL   CONTROLS COMPUTING/PRINTING OF TRUE GLOBAL NORMS OF FIELDS
!                            FROM/TO THE ATMOS MODEL
!      *LLNORMIFS2WAM* LOGICAL IF TRUE NORMS FOR FIELDS PASSED FROM IFS TO WAM WILL BE PRODUCED
!      *LLNORMWAM2IFS* LOGICAL IF TRUE NORMS FOR FIELDS PASSED FROM WAM TO IFS WILL BE PRODUCED
!      *LLNORMWAMOUT* LOGICAL IF TRUE NORMS OF SELECTED OUPTUT FIELDS WILL BE PRODUCED
!      *LLNORMWAMOUT_GLOBAL* LOGICAL IF TRUE NORMS OF SELECTED OUPTUT FIELDS WILL BE GLOBAL (see above) 
!      *LMASK_OUT_NOT_SET    INDICATES IF THE MASK USED FOR FIELDS RETURNED
!                            TO IFS IS UNSET OR NOT. 
!      *LMASK_TASK_STR* LOGICAL TRUE UNTIL THE TASK STRUCTURE CORRESPONDING
!                            TO MASK_OUT IS DETERMINED.
!      *KCOUSTEP*  INTEGER   COUPLING TIME TO THE IFS (in seconds).
!      *LFROMTASK* INTEGER   CONTROLS WHICH WAM TASKS CONTRIBUTE TO THE FIELDS
!                            RETURNED TO THE IFS FROM CURRENT TASK
!                            BY SPECIFYING THE NUMBER OF SEA POINTS THAT
!                            CONTRIBUTES TO THE FIELDS
!      *LTOTASK*   INTEGER   CONTROLS WHICH WAM TASKS NEED TO RECEIVE
!                            CONTRIBUTIONS TO THE FIELDS RETURNED TO IFS
!                            FROM CURRENT WAM TASK BY SPECIFYING
!                            THE NUMBER OF SEA POINTS THAT ARE NEEDED.
!      *IJFROMTASK*INTEGER   GIVES THE (global) IJ INDEX FOR EACH SEA POINT
!                            REFERRED TO BY LFROMTASK.
!                            SIZE IS GIVEN BY NFROMTASKS
!      *IJTOTASK*  INTEGER   GIVES THE (global) IJ INDEX FOR EACH SEA POINT
!                            REFERRED TO BY LTOTASK
!                            SIZE IS GIVEN BY NTOTASKS.
!      *ISTFROMTASK*INTEGER  GIVES THE STARTNG INDEX IN IJFROMTASK FOR ALL
!                            IJ's THAT ARE FROM EACH TASK (if any).
!      *ISTTOTASK*  INTEGER  GIVES THE STARTNG INDEX IN IJTOTASK FOR ALL
!                            IJ's THAT ARE TO BE SENT FROM EACh TASK (if any).
!      *NFROMTASKS*INTEGER   SUM OF LFROMTASKS ON EACH TASK.
!      *NTOTASKS*  INTEGER   SUM OF LTOTASKS ON EACH TASK.
!      *I_MASK_IN* INTEGER   LIST OF I INDEX OF MASK_IN THAT ARE LOCAL TO TASK
!      *N_MASK_IN* INTEGER   MAXIMUM SIZE OF I_MASK_IN
!      *I_MASK_OUT*INTEGER   LIST OF I INDEX OF MASK_OUT THAT ARE LOCAL TO TASK
!      *J_MASK_OUT*INTEGER   LIST OF J INDEX OF MASK_OUT THAT ARE LOCAL TO TASK
!      *N_MASK_OUT*INTEGER   MAXIMUM SIZE OF I_MASK_OUT AND J_MASK_OUT 
!      *LLCAPCHNK* LOGICAL   IF TRUE CHARNOCK FOR HIGh WINDS WILL BE CAPPED (see chnkmin)
!      *BETAMAX*   REAL      PARAMETER FOR WIND INPUT.
!      *ZALP*      REAL      SHIFTS GROWTH CURVE.
!      *TAUWSHELTER* REAL    SHELTERING COEFFICIENT in METEO FRANCE PHYSICS
!      *ITSHELT*   INTEGER   =0 IF TAUWSHELTER<=0.0 ELSE =1
!      COMPUTE LAST FREQUENCY INDEX OF PROGNOSTIC PART OF SPECTRUM.
!      FREQUENCIES LE MAX(TAILFACTOR*MAX(FMNWS,FM),TAILFACTOR_PM*FPM),
!      WHERE FPM IS THE PIERSON-MOSKOWITZ FREQUENCY BASED ON FRICTION
!      VELOCITY. (FPM=G/(FRIC*ZPI*USTAR))
!      *ALPHA*     REAL      MINIMUM CHARNOCK CONSTANT WITH NO WAVES.
!      *XKAPPA*    REAL      VON KARMAN CONSTANT.
!      *RNU*       REAL      KINEMATIC AIR VISCOSITY
!      *RNUM*      REAL      REDUCED KINEMATIC AIR VISCOSITY FOR MOMENTUM TRANSFER
!      *XNLEV*     REAL      WIND SPEED REFERENCE HEIGHT

!      *JTOT_TAUHF INTEGER   DIMENSION OF WTAUHF. IT MUST BE ODD !!! 
!      *WTAUHF*    REAL      INTEGRATION WEIGHT FOR TAU_PHI_HF
!      *X0TAUHF*   REAL      LOWEST LIMIT FOR INTEGRATION IN TAU_PHI_HF: X0 *(G/USTAR)
!
!      INSTANTANEOUS FIELDS PASSED TO NEMO:
!      *NSWH*      REAL      SIGNIFICANT WAVE HEIGHT FOR NEMO
!      *NMWP*      REAL      MEAN WAVE PERIOD FOR NEMO
!      *NPHIEPS*   REAL      NORMALIZED ENERGY FLUX TO OCEAN FOR NEMO
!      *NTAUOC*    REAL      NORMALIZED MOMENTUM FLUX INTO OCEAN FOR NEMO.
!      *NEMOSTRN   REAL      SEA ICE MEAN SQUARE WAVE STRAIN FOR NEMO
!      *NEMOUSTOKES REAL     U-COMPONENT OF SURFACE STOKES DRIFT FOR NEMO 
!      *NEMOVSTOKES REAL     V-COMPONENT OF SURFACE STOKES DRIFT FOR NEMO 

!      ACCUMULATED FIELDS PASSED TO NEMO:
!      *NEMONTAU*  INTEGER   ACCUMULATION COUNT
!      *NEMOTAUX*  REAL      NEMO U OCEAN STRESS
!      *NEMOTAUY*  REAL      NEMO V OCEAN STRESS
!      *NEMONEW10* REAL      NEMO NEUTRAL 10M WIND
!      *NEMOPHIF*  REAL      TURBULENT KINETIC ENERGY FLUX INTO THE OCEAN
!
!      *NEMOINIDATE* INTEGER NEMO INITIAL DATE
!      *NEMOINITIME* INTEGER NEMO INITIAL TIME
!      *NEMOITINI*   INTEGER NEMO INITIAL TIME STEP
!      *NEMOITEND*   INTEGER NEMO FINAL TIME STEP
!      *NEMOTSTEP*   REAL    NEMO TIMESTEP
!      *NEMOFRCO*    INTEGER NEMO COUPLING FREQ IN WAM TIME STEPS
!      *NEMONSTEP*   INTEGER NEMO COUPLING FREQ IN NEMO TIME STEPS
!      *NEMOCSTEP*   INTEGER NEMO CURRENT TIME STEP
!      *NEMOWSTEP*   INTEGER WAM  CURRENT TIME STEP

!      *IFSTSTEP*    TIME STEP OF ATMOSPHERIC MODEL
!      *IFSNSTEP*    CURRENT STEP OF ATMOSPHERIC MODEL
!      *LIFS_IO_SERV_ENABLED* LOGICAL TRUE IF IFS IO SERVER ENABLED

! ----------------------------------------------------------------------
      END MODULE YOWCOUP
