      MODULE YOWCURR

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *CURRENT* - CURRENT FIELD.

      REAL(KIND=JWRB), PARAMETER :: CURRENT_MAX=2.0_JWRB

      REAL(KIND=JWRB), ALLOCATABLE :: U(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: V(:,:) 

      CHARACTER(LEN=14) :: CDTCUR
      CHARACTER(LEN=14) :: CDATECURA

      INTEGER(KIND=JWIM) :: IDELCUR

      LOGICAL :: LLCHKCFL
      LOGICAL :: LLCHKCFLA

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -----     --------
!      CURRENT_MAX REAL      MAXIMUM VALUE ALLOWED FOR EACH CURRENT COMPONENT (M/S)
!      *U*         REAL      U - COMPONENT OF CURRENT (M/S).
!      *V*         REAL      V - COMPONENT OF CURRENT (M/S).
!      *CDTCUR*    CHAR*14   REFERENCE DATE FOR U AN V.
!      *CDATECURA* CHAR*14   INITIAL DATE FOR INPUT OF U AND V.
!      *IDELCUR*   INTEGER   CURRENT INPUT STEP IN SECONDS.
!      *LLCHKCFL*  LOGICAL   TRUE IF THE CFL CRITERIA HAVE TO BE CHECKED 
!      *LLCHKCFLA* LOGICAL   TRUE IF THE CFL CRITERIA HAVE TO BE CHECKED
!                            AT ALL TIME STEPS (when currents are updated). 

! ----------------------------------------------------------------------
      END MODULE YOWCURR
