      MODULE YOWDRVTYPE

!     DERIVED TYPES DEFINITION:

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    **  *VARIABLES DEPENDENT ON FREQUENCY (but not direction)
!          i.e. wave properties dependent on water depth or sea ice

      TYPE FREQUENCY 
        REAL(KIND=JWRB) :: WAVNUM     ! WAVE NUMBER
        REAL(KIND=JWRB) :: CINV       ! RECIPROCAL OF THE PHASE VELOCITY (1/c)
        REAL(KIND=JWRB) :: CGROUP     ! GROUP SPEED
        REAL(KIND=JWRB) :: OMOSNH2KD  ! OMEGA / SINH(2KD)
        REAL(KIND=JWRB) :: STOKFAC    ! FACTOR TO COMPUTE SURFACE STOKES DRIFT FROM SPECTRUM 2*G*K**2/(OMEGA*TANH(2KD))
        REAL(KIND=JWRB) :: CIWA       ! SEA ICE WAVE ATTENUATION
      END TYPE FREQUENCY 


!*    **  *VARIABLES USED FOR FORCING INPUT AND COMPUTATIONS.
!          See *INIT_FIELDG* for the initialisation

      TYPE FORCING_FIELDS 
        REAL(KIND=JWRB) :: UWND    ! U COMPONENT ON WAVE MODEL GRID of
                        ! 10m wind, or friction velocity or surfact stress
                        ! See ICODE and ICODE_CPL
        REAL(KIND=JWRB) :: VWND    ! V COMPONENT ON WAVE MODEL GRID of
                        ! 10m wind, or friction velocity or surfact stress
                        ! See ICODE and ICODE_CPL
        REAL(KIND=JWRB) :: AIRD    ! AIR DENSITY ON WAVE MODEL GRID
        REAL(KIND=JWRB) :: WSTAR   ! CONVECTIVE VELOCITY ON WAVE MODEL GRID
        REAL(KIND=JWRB) :: CICOVER ! SEA ICE FRACTION ON WAVE MODEL GRID 
        REAL(KIND=JWRB) :: CITHICK ! SEA ICE THICKNESS ON WAVE MODEL GRID 
        REAL(KIND=JWRB) :: LKFR    ! LAKE FRACTION ON WAVE MODEL GRID 
        REAL(KIND=JWRB) :: UCUR    ! U COMPONENT OF CURRENT ON WAVE MODEL GRID
        REAL(KIND=JWRB) :: VCUR    ! V COMPONENT OF CURRENT ON WAVE MODEL GRID
        REAL(KIND=JWRB) :: WSWAVE  ! WIND SPEED (WAVE PARAMETER 245) ON WAVE MODEL GRID
        REAL(KIND=JWRB) :: WDWAVE  ! WIND DIRECTION (WAVE PARAMETER 249) ON WAVE MODEL GRID
        REAL(KIND=JWRB) :: UFRIC   ! FRICTION VELOCITY 
        REAL(KIND=JWRB) :: TAUW    ! WAVE INDUCED KINEMATIC STRESS MAGNITUDE
        REAL(KIND=JWRB) :: TAUWDIR ! WAVE INDUCED KINEMATIC STRESS DIRECTION 
        REAL(KIND=JWRB) :: Z0M     ! SURFACE ROUGHNESS LENGTH SCALE
        REAL(KIND=JWRB) :: Z0B     ! BACKGROUND SURFACE ROUGHNESS LENGTH SCALE
        REAL(KIND=JWRB) :: CHNK    ! CHARNOCK COEFFICIENT
        REAL(KIND=JWRB) :: XLON    ! LONGITUDE OF FORCING_FIELDS DATA THAT ARE NEEDED (i.e. all local points only !) 
        REAL(KIND=JWRB) :: YLAT    ! LATITUDE  OF FORCING_FIELDS DATA THAT ARE NEEDED (i.e. all local points only !) 
      END TYPE FORCING_FIELDS


!*    **  *VARIABLES USED FOR OUTPUT OF INTEGRATED/DERIVED 2D FIELDS
!          SEE *WVALLOC* AND *WVDEALLOC* FOR THEIR MANAGEMENT

      TYPE INTGT_PARAM_FIELDS 
        REAL(KIND=JWRB) :: WSEMEAN  ! WINDSEA VARIANCE.
        REAL(KIND=JWRB) :: WSFMEAN  ! WINDSEA MEAN FREQUENCY (1./MEAN PERIOD).

        REAL(KIND=JWRB) :: USTOKES  ! U-COMP SURFACE STOKES DRIFT.
        REAL(KIND=JWRB) :: VSTOKES  ! V-COMP SURFACE STOKES DRIFT.

        REAL(KIND=JWRB) :: PHIEPS   ! NORMALIZED ENERGY FLUX TO OCEAN.
        REAL(KIND=JWRB) :: PHIOCD   ! DIMENSIONAL TURBULENT ENERGY FLUX INTO OCEAN.

        REAL(KIND=JWRB) :: PHIAW    ! NORMALIZED ENERGY FLUX FROM WIND TO WAVES.

        REAL(KIND=JWRB) :: TAUOC    ! NORMALIZED MOMENTUM FLUX INTO OCEAN.
        REAL(KIND=JWRB) :: TAUXD    ! DIMENSIONAL U-COMPONENT OF MOMENTUM FLUX FROM ATMOSPHERE.
        REAL(KIND=JWRB) :: TAUYD    ! DIMENSIONAL V-COMPONENT OF MOMENTUM FLUX FROM ATMOSPHERE.
        REAL(KIND=JWRB) :: TAUOCXD  ! DIMENSIONAL U-COMPONENT OF MOMENTUM FLUX INTO OCEAN.
        REAL(KIND=JWRB) :: TAUOCYD  ! DIMENSIONAL V-COMPONENT OF MOMENTUM FLUX INTO OCEAN.

        REAL(KIND=JWRB) :: STRNMS   ! MEAN SQUARE STRAIN INTO THE SEA ICE.

        REAL(KIND=JWRB) :: ALTWH    ! ALTIMETER WAVE HEIGHT
        REAL(KIND=JWRB) :: CALTWH   ! CORRECTED ALTIMETER WAVE HEIGHT
        REAL(KIND=JWRB) :: RALTCOR  ! ALTIMETER RANGE CORRECTION

      END TYPE INTGT_PARAM_FIELDS 

! ----------------------------------------------------------------------

      END MODULE YOWDRVTYPE
