      MODULE YOWFRED

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *FREDIR* - FREQUENCY AND DIRECTION GRID.

      REAL(KIND=JWRB), ALLOCATABLE :: FR(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIM(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIM_SIM(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIMOFR(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIMOFR_SIM(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIM_END_L(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIM_END_U(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIMFR(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIMFR_SIM(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIMFR2(:)
      REAL(KIND=JWRB), ALLOCATABLE :: DFIMFR2_SIM(:)
      REAL(KIND=JWRB), ALLOCATABLE :: GOM(:)
      REAL(KIND=JWRB), ALLOCATABLE :: C(:)
      REAL(KIND=JWRB)              :: DELTH
      REAL(KIND=JWRB)              :: DELTR
      REAL(KIND=JWRB), ALLOCATABLE :: TH(:)
      REAL(KIND=JWRB), ALLOCATABLE :: COSTH(:)
      REAL(KIND=JWRB), ALLOCATABLE :: SINTH(:)
      REAL(KIND=JWRB), ALLOCATABLE :: FR5(:)
      REAL(KIND=JWRB), ALLOCATABLE :: FRM5(:)
      REAL(KIND=JWRB), ALLOCATABLE :: COFRM4(:)

      REAL(KIND=JWRB), ALLOCATABLE :: FLMAX(:)

      REAL(KIND=JWRB), PARAMETER   :: FRATIO = 1.1_JWRB
      REAL(KIND=JWRB), PARAMETER   :: WETAIL = 0.25_JWRB
      REAL(KIND=JWRB), PARAMETER   :: FRTAIL = 0.2_JWRB
      REAL(KIND=JWRB), PARAMETER   :: WP1TAIL = 1.0_JWRB/3.0_JWRB 
      REAL(KIND=JWRB), PARAMETER   :: WP2TAIL = 0.5_JWRB
      REAL(KIND=JWRB), PARAMETER   :: QPTAIL = 2.0_JWRB/9.0_JWRB 
      REAL(KIND=JWRB), PARAMETER   :: COEF4 = 3.0E-07_JWRB

      REAL(KIND=JWRB), PARAMETER   :: FRIC = 28.0_JWRB
      REAL(KIND=JWRB), PARAMETER   :: OLDWSFC = 1.2_JWRB
      REAL(KIND=JWRB)              :: FLOGSPRDM1

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *FR*        REAL      FREQUENCIES IN HERTZ.
!      *DFIM*      REAL      FREQUENCY INTERVAL*DIRECTION INTERVAL.
!                            FOR TRAPEZOIDAL RULE
!      *DFIM_SIM*  REAL      FREQUENCY INTERVAL*DIRECTION INTERVAL.
!                            FOR SIMPSON RULE
!      *DFIMOFR*   REAL      DFIM/FR
!      *DFIMOFR_SIMREAL      DFIM_SIM/FR
!      *DFIM_END_L REAL      FREQUENCY INTERVAL*DIRECTION INTERVAL
!                            FOR LOWER BOUND FOR TRAPEZOIDAL INTEGRATION  WHERE
!                            DFIM IS USED IN BETWEEN DFIM_END_L AND DFIM_END_U
!      *DFIM_END_U REAL      FREQUENCY INTERVAL*DIRECTION INTERVAL
!                            FOR UPPER BOUND FOR TRAPEZOIDAL INTEGRATION WHERE
!                            DFIM IS USED IN BETWEEN DFIM_END_L AND DFIM_END_U
!      *DFIMFR*    REAL      DFIM*FR
!      *DFIMFR_SIM REAL      DFIM_SIM*FR
!      *DFIMFR2*   REAL      DFIM*FR**2
!      *DFIMFR2_SIMREAL      DFIM_SIM*FR**2
!      *GOM*       REAL      DEEP WATER GROUP VELOCITIES (M/S).
!      *C*         REAL      DEEP WATER PHASE VELOCITIES (M/S).
!      *DELTH*     REAL      ANGULAR INCREMENT OF SPECTRUM (RADIANS).
!      *DELTR*     REAL      DELTH TIMES RADIUS OF EARTH (METRES).
!      *TH*        REAL      DIRECTIONS IN RADIANS.
!      *COSTH*     REAL      COS OF DIRECTION.
!      *SINTH*     REAL      SIN OF DIRECTION.
!      *FR5*       REAL      FR(M)**5 
!      *FRM5*      REAL      (1./FR(M))**5 
!      *COFRM4*    REAL      COEF4*G*FR(M)**(-4.) 
!      *FLMAX*     REAL      MAXIMUM SPECTRAL COMPONENT ALLOWED.
!                            (ALPHAPMAX/PI) (G**2/(2PI)**4) FR(M)**-5
!                            ALPHAPMAX MAXIMUM PHILLIPS PARAMETER (SEE USERIN).  
!      *FRATIO*    REAL      FREQUENCY RATIO.
!      *WETAIL*    REAL      WAVE ENERGY TAIL CONSTANT FACTOR.
!      *FRTAIL*    REAL      FREQUENCY TAIL CONSTANT FACTOR.
!      *WP1TAIL*   REAL      PERIOD 1 TAIL CONSTANT FACTOR.
!      *WP2TAIL*   REAL      PERIOD 2 TAIL CONSTANT FACTOR.
!      *QPTAIL*    REAL      GODA TAIL CONSTANT FACTOR.
!      *COEF4*     REAL      COEFFICIENT USED TO COMPUTE THE SPECTRAL
!                            LIMITER IN IMPLSCH.
!      *FRIC*      REAL      COEFFICIENT RELATING THE PIERSON-MOSKOVITCH
!                            ANGULAR FREQUENCY OF THE SPECTRAL PEAK
!                            TO THE FRICTION VELOCITY:
!                            OMEGA_PM=G/(FRIC*USTAR) 
!      *OLDWSFC*  REAL       OLD WIND SEA FACTOR USED TO DETERMINE THE THRESHOLD
!                            FOR WINDSEA/SWELL SEPARATION
!      *FLOGSPRDM1* REAL     FLOGSPRDM1=1./LOG10(FRATIO)
! ----------------------------------------------------------------------
      END MODULE YOWFRED
