      MODULE YOWFPBO

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *FPBOUN* USED FOR THE FINE GRID
!                       ORGANIZATION THE BOUNDARY POINTS.

      INTEGER(KIND=JWIM)              :: IBOUNF
      INTEGER(KIND=JWIM)              :: NBOUNF
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJARF(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IGARF(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IBFL(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IBFR(:)

      REAL(KIND=JWRB), ALLOCATABLE    :: BFW(:)

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *IBOUNF*    INTEGER   FLAG FOR THE FINE GRID INPUT OF BOUNDARY VALUES.
!                            = 1; THE RUN INCLUDES INPUT BOUNDARY POINTS.
!                            ELSE; NO BOUNDARY POINTS.
!      *NBOUNF*    INTEGER   NUMBER OF FINE GRID BOUNDARY POINTS.
!      *IGARF*     INTEGER   BLOCK INDEX FOR A FINE GRID BOUNDARY POINT.
!      *IJARF*     INTEGER   POINT INDEX FOR A FINE GRID BOUNDARY POINT.
!      *IBFL*      INTEGER   INDEX OF LEFT COARSE GRID OUTPUT POINT.
!      *IBFR*      INTEGER   INDEX OF RIGHT COARSE GRID OUTPUT POINT.
!      *BFW*       REAL      SPACE INTERPOLATION WEIGHT.

! ----------------------------------------------------------------------
      END MODULE YOWFPBO
