      MODULE YOWGRIB_HANDLES

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE
!     GRIB HANDLES
      SAVE
      INTEGER(KIND=JWIM) :: NGRIB_HANDLE_WAM_I = -99   ! GRIB TEMPLATE FOR WAM INTEGRATED PARAMETERS.
      INTEGER(KIND=JWIM) :: NGRIB_HANDLE_WAM_S = -99   ! GRIB TEMPLATE FOR WAM SPECTRA.
      INTEGER(KIND=JWIM) :: NGRIB_HANDLE_IFS   = -99     ! FOR IFS FIELDS PASSED TO WAM.
      END MODULE YOWGRIB_HANDLES
