      MODULE YOWGRID

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *GRIDPAR*  GENERAL GRID INFORMATION.

      REAL(KIND=JWRB)              :: DELPHI 
      REAL(KIND=JWRB), ALLOCATABLE :: DELLAM(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: DELLAM1(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: SINPH(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: COSPH(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: COSPHM1(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: CDR(:,:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: SDR(:,:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: PRQRT(:,:)

      INTEGER(KIND=JWIM), ALLOCATABLE :: NLONRGG(:) 
      INTEGER(KIND=JWIM)              :: IGL 
      INTEGER(KIND=JWIM)              :: IJSLOC, IJLLOC, IJGLOBAL_OFFSET
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJS(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJL2(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJLS(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJL(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJLT(:) 

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *DELPHI*    REAL      GRID INCREMENT FOR LATITUDE (METRES).
!      *DELLAM*    REAL      GRID INCREMENT FOR LONGITUDE AT EQUATOR
!                            IN METRES.
!      *DELLAM1*   REAL      1./DELLAM AT BLOCK POINTS (IJ's).
!      *SINPH*     REAL      SIN OF LATITUDE.
!      *COSPH*     REAL      COS OF LATITUDE.
!      *COSPHM1*   REAL      1./COSPH AT BLOCK POINTS (IJ's).
!      *CDR*       REAL      ADVECTION VELOCITY IN SE-NW DIRECTION WHEN
!                            GRID ROTATED BY 45 DEGREES.
!      *SDR*       REAL      ADVECTION VELOCITY IN SW-NE DIRECTION WHEN
!                            GRID ROTATED BY 45 DEGREES.
!      *PRQRT*     REAL      PERCENTAGE OF THE ROTATED (45 degree) GRID
!                            USED FOR THE PROPAGATION (see PROPAGS1).
!                            IT IS 50% EXCEPT IF FOR STABILITY REASON
!                            IT HAS TO BE DECREASED ABOVE ~75 DEGREE
!      *IGL*       INTEGER   NO OF BLOCKS.
!      *IJSLOC*    INTEGER   INDEX OF FIRST LOCAL POINT
!      *IJLLOC*    INTEGER   INDEX OF LAST LOCAL POINT
!      *IJGLOBAL_OFFSET INTEGER OFFSET TO PLACE FIRST LOCAL POINT IN
!                            GLOBAL ARRAY
!      *IJS*       INTEGER   INDEX OF FIRST POINT OF SECOND LAT.
!      *IJS*       INTEGER   INDEX OF FIRST POINT OF SECOND LAT.
!      *IJL2*      INTEGER   INDEX OF LAST POINT OF SECOND LAT.
!      *IJLS*      INTEGER   INDEX OF FIRST POINT OF LAT BEFORE LAST.
!      *IJL*       INTEGER   INDEX OF LAST POINT OF LAT BEFORE LAST.
!      *IJLT*      INTEGER   TOTAL NUMBER OF GRIDPOINTS IN A BLOCK.

! ----------------------------------------------------------------------
      END MODULE YOWGRID
