      MODULE YOWINTP

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *INTPAR*  GRIDDED INTEGRATED PARAMETER TOTAL SPECTRUM.

      REAL(KIND=JWRB), ALLOCATABLE :: GOUT(:,:,:) 

!!!!!!!!!!!! with the introduction of GOUT all the fields below
!!!!!!!!!!! should be obsolete. Still need to clean the mess in the
!!!!!!!!!!! unwam part of the code
      REAL(KIND=JWRB), ALLOCATABLE :: WHGTTG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WDIRTG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WPKFTG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WMNFTG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: USTARG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: UDIRG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TAUWG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: CDG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: SMEANG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: U10G(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WHGTAG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: CWHTAG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: RANGAG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: MWP1G(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: MWP2G(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WSPRDG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: C3G(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: C4G(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: BFG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: QPG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: DEPTHG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: HMAXG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TMAXG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: USTOKESG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: VSTOKESG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: UCURG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: VCURG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: PHIEPSG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: PHIAWG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TAUOCG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: STRNMSG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: RHOAG(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WSTARG(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: CICG(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: CIHG(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E10G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WEFLXMG(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WEFLXDG(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E1012G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E1214G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E1417G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E1721G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E2125G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: E2530G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX1G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX2G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX3G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX4G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX5G(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: NSSTG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: NICCG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: NICTG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: NUCUG(:,:) 
      REAL(KIND=JWRB), ALLOCATABLE :: NVCUG(:,:) 

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *GOUT*      REAL      GRIDDED OUTPUT PARAMETERS

!      *WHGTTG*    REAL      GRIDDED MEAN ENERGY (M*M) CHANGED TO
!                            WAVE HEIGHT (M) IN SUB MAKEGRID.
!      *WDIRTG*    REAL      GRIDDED MEAN DIRECTION (RAD) CHANGED TO
!                            DEGREE AND METEOROLOGICAL DEFINITION
!                            IN SUB OUTINT.
!      *WPKFTG*    REAL      GRIDDED PEAK FREQUENCY (HZ) until gribbing
!                            where it is transformed into PERIOD.
!      *WMNFTG*    REAL      GRIDDED MEAN FREQUENCY (HZ) until gribbing
!                            where it is transformed into PERIOD.
!      *USTARG*    REAL      GRIDDED FRICTION VELOCITY (M/S).
!      *UDIRG*     REAL      GRIDDED WIND DIRECTION (RAD) CHANGED TO
!                            DEGREE IN SUB OUTINT.
!      *TAUWG*     REAL      GRIDDED NORMALISED WAVE STRESS.
!      *CDG*       REAL      GRIDDED DRAG COEFFICENT.
!      *SMEANG*    REAL      GRIDDED MEAN SQUARE SLOPE.
!      *U10G*      REAL      GRIDDED WIND SPEED (M/S).
!      *WHGTAG*    REAL      GRIDDED ALTIMETER WAVE HEIGHT (M).
!      *CWHTAG*    REAL      GRIDDED CORRECTED ALTIMETER WAVE HEIGHT (M) 
!      *RANGAG*    REAL      GRIDDED RELATIVE CORRECTION TO THE
!                            ALTIMETER RANGE.
!      *MWP1G*     REAL      GRIDDED MEAN WAVE PERIOD 1 (S.).
!      *MWP2G*     REAL      GRIDDED MEAN WAVE PERIOD 2 (S.).
!      *WSPRDG*    REAL      GRIDDED DIRECTIONAL SPREAD (-). 
!      *C3G*       REAL      GRIDDED SKEWNESS KURTOSIS (-). 
!      *C4G*       REAL      GRIDDED SPECTRAL KURTOSIS (-). 
!      *BFG*       REAL      GRIDDED BENJAMIN-FEIR INDEX (-). 
!      *QPG*       REAL      GRIDDED SPECTRAL PEAKEDNESS (-). 
!      *DEPTHG*    REAL      GRIDDED MODEL DEPTH.
!      *HMAXG*     REAL      GRIDDED MAXIMUM WAVE HEIGHT FIELD (M).
!      *TMAXG*     REAL      GRIDDED MAXIMUM WAVE PERIOD FIELD (S).
!      *USTOKESG*  REAL      GRIDDED U-COMP STOKES DRIFT (M/S).
!      *VSTOKESG*  REAL      GRIDDED V-COMP STOKESDRIFT (M/S).
!      *UCURG*     REAL      GRIDDED U-COMP SURFACE CURRENT (M/S).
!      *VCURG*     REAL      GRIDDED V-COMP SURFACE CURRENT (M/S).
!      *PHIEPSG*   REAL      GRIDDED NORMALIZED ENERGYFLUX TO OCEAN.
!      *PHIAWG*    REAL      GRIDDED NORMALIZED ENERGY FLUX TO WAVES.
!      *TAUOCG*    REAL      GRIDDED NORMALIZED MOMENTUMFLUX TO OCEAN.
!      *STRNMSG*   REAL      GRIDDED MEAN SQUARE STRAIN IN THE SEA ICE.
!      *RHOAG*     REAL      GRIDDED AIR DENSITY OVER OCEANS.
!      *WSTARG*    REAL      GRIDDED FREE CONVECTIVE VELOCITY SCALE.
!      *CICG*      REAL      GRIDDED SEA ICE COVER
!      *CIHG*      REAL      GRIDDED SEA ICE THICKNESS
!      *E10G*      REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD > 10s
!      *WEFLXMG*   REAL      GRIDDED WAVE ENERGY FLUX MAGNITUDE
!      *WEFLXDG*   REAL      GRIDDED WAVE ENERGY FLUX MEAN DIRECTION 
!      *E1012G*    REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD BETWEEN 10 AND 12 SECONDS
!      *E1214G*    REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD BETWEEN 12 AND 14 SECONDS
!      *E1417G*    REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD BETWEEN 14 AND 17 SECONDS
!      *E1721G*    REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD BETWEEN 17 AND 21 SECONDS
!      *E2125G*    REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD BETWEEN 21 AND 25 SECONDS
!      *E2530G*    REAL      GRIDDED SPECTRAL VARIANCE WITH PERIOD BETWEEN 25 AND 30 SECONDS
!      *WX1G*      REAL      GRIDDED WAVE EXPERIMENTAL PARAMETER.
!      *WX2G*      REAL      GRIDDED WAVE EXPERIMENTAL PARAMETER.
!      *WX3G*      REAL      GRIDDED WAVE EXPERIMENTAL PARAMETER.
!      *WX4G*      REAL      GRIDDED WAVE EXPERIMENTAL PARAMETER.
!      *WX5G*      REAL      GRIDDED WAVE EXPERIMENTAL PARAMETER.
!      *NSSTG*     REAL      GRIDDED NEMO SST
!      *NICCG*     REAL      GRIDDED NEMO ICE COVER
!      *NICTG*     REAL      GRIDDED NEMO ICE THICKNESS
!      *NUCUG*     REAL      GRIDDED NEMO U-CURRENT
!      *NVCUG*     REAL      GRIDDED NEMO V-CURRENT


! ----------------------------------------------------------------------
      END MODULE YOWINTP
