      MODULE YOWMEAN

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
      USE YOWNEMOP, ONLY : NEMODP

      IMPLICIT NONE

!*    **  *MEANPA* - INTEGRATED PARAMETERS OF A BLOCK.


!!!! some of those fields are obsoleter. WIll need to celan up !!!!

      REAL(KIND=JWRB), ALLOCATABLE :: EMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: FMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: CDMEAN(:)
      REAL(KIND=JWRB), ALLOCATABLE :: WVSTRMEAN(:)
      REAL(KIND=JWRB), ALLOCATABLE :: NSWH(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: NMWP(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: THQ(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: SMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: ALTWH(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: CALTWH(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: RALTCOR(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: P1MEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: P2MEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: SPRDMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: C3MEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: C4MEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: BFMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: QPMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: HMAXMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: FPMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TMAXMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: ETAMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: RMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: XNSLCMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: SIGTHMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: EPSMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: USTMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: VSTMEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: PHIEPS(:) 

      REAL(KIND=NEMODP),ALLOCATABLE :: NPHIEPS(:) 

      REAL(KIND=JWRB), ALLOCATABLE :: PHIAW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TAUOC(:) 

      REAL(KIND=NEMODP),ALLOCATABLE :: NTAUOC(:) 

      REAL(KIND=JWRB), ALLOCATABLE :: STRNMS(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E10MEAN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WEFLXM(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WEFLXD(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E1012(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E1214(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E1417(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E1721(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E2125(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: E2530(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WX1(:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX2(:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX3(:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX4(:)
      REAL(KIND=JWRB), ALLOCATABLE :: WX5(:)

!*     VARIABLE.      TYPE.     PURPOSE.
!      ---------      -------   --------
!      *EMEAN*        REAL      TOTAL ENERGY.
!      *FMEAN*        REAL      MEAN FREQUENCY (1./MEAN PERIOD).
!      *CDMEAN*       REAL      DRAG COEFFICIENT
!      *WVSTRMEAN*    REAL      WAVE INDUCED STRESS
!      *NSWH*         REAL      SIGNIFICANT WAVE HEIGHT FOR NEMO
!      *NMWP*         REAL      MEAN WAVE PERIOD FOR NEMO
!      *THQ*          REAL      MEAN WAVE DIRECTION IN RADIANS.
!      *SMEAN*        REAL      MEAN SQUARE SLOPE.
!      *ALTWH*        REAL      ALTIMETER WAVE HEIGHT 
!      *CALTWH*       REAL      CORRECTED ALTIMETER WAVE HEIGHT 
!      *RALTCOR*      REAL      ALTIMETER RANGE CORRECTION 
!      *P1MEAN*       REAL      MEAN PERIOD (1).
!      *P2MEAN*       REAL      MEAN PERIOD (2).
!      *SPRDMEAN*     REAL      MEAN DIRECTIONAl SPREAD.
!      *C3MEAN*       REAL      SURFACE ELEVATION SKEWNESS.
!      *C4MEAN*       REAL      SURFACE ELEVATION KURTOSIS.
!      *BFMEAN*       REAL      BENJAMIN-FEIR INDEX.
!      *QPMEAN*       REAL      SPECTRAL PEAKEDNESS.
!      *HMAXMEAN*     REAL      MAXIMUM WAVE HEIGHT.
!      *FPMEAN*       REAL      PEAK FREQUENCY FROM 1D SPECTRUM.
!      *TMAXMEAN*     REAL      MAXIMUM PERIOD CORRESPONDING TO MAXIMUM
!                               WAVE HEIGHT.
!      *ETAMEAN*      REAL      WAVE-INDUCED MEAN SURFACE ELEVATION. 
!      *RMEAN         REAL      DIMENSIONLESS RATIO OF ANGULAR AND FREQUENCY WIDTH
!      *XNSLCMEAN     REAL      NUMBER OF EVENTS ENTERING INTO THE CALCULATION OF FREAK WAVE PARAMETERS
!      *SIGTHMEAN     REAL      RELATIVE WIDTH IN DIRECTION 
!      *EPSMEAN       REAL      MEAN WAVE STEEPNESS AT  
!      *USTMEAN*      REAL      U-COMP STOKES DRIFT.
!      *VSTMEAN*      REAL      V-COMP STOKES DRIFT.
!      *PHIEPS*       REAL      NORMALIZED ENERGY FLUX TO OCEAN.
!      *NPHIEPS*      REAL      COPY OF PHIEPS FOR NEMO
!      *PHIAW*        REAL      NORMALIZED ENERGY FLUX FROM WIND TO WAVES.
!      *TAUOC*        REAL      NORMALIZED MOMENTUM FLUX INTO OCEAN.
!      *NTAUOC*       REAL      COPY OF TAUOC FOR NEMO.
!      *STRNMS*       REAL      MEAN SQUARE STRAIN INTO THE SEA ICE.
!      *E10MEAN*      REAL      SPECTRAL VARIANCE WITH PERIOD > 10s  
!      *WEFLXM*       REAL      WAVE ENERGY FLUX MAGNITUDE
!      *WEFLXD*       REAL      WAVE ENERGY FLUX MEAN DIRECTION 
!      *E1012*        REAL      SPECTRAL VARIANCE WITH PERIOD BETWEEN 10 AND 12 SECONDS
!      *E1214*        REAL      SPECTRAL VARIANCE WITH PERIOD BETWEEN 12 AND 14 SECONDS
!      *E1417*        REAL      SPECTRAL VARIANCE WITH PERIOD BETWEEN 14 AND 17 SECONDS
!      *E1721*        REAL      SPECTRAL VARIANCE WITH PERIOD BETWEEN 17 AND 21 SECONDS
!      *E2125*        REAL      SPECTRAL VARIANCE WITH PERIOD BETWEEN 21 AND 25 SECONDS
!      *E2530*        REAL      SPECTRAL VARIANCE WITH PERIOD BETWEEN 25 AND 30 SECONDS

! ----------------------------------------------------------------------
      END MODULE YOWMEAN
