      MODULE YOWMPP

      IMPLICIT NONE

!*    ** *MPP* - MESSAGE PASSING PARAMETERS.

      INTEGER(KIND=JWIM) :: IRANK 
      INTEGER(KIND=JWIM) :: NPROC 
      INTEGER(KIND=JWIM) :: NPREVIOUS 
      INTEGER(KIND=JWIM) :: NNEXT 
      INTEGER(KIND=JWIM) :: NINF 
      INTEGER(KIND=JWIM) :: NSUP 
      INTEGER(KIND=JWIM) :: MPMAXLENGTH 
      INTEGER(KIND=JWIM) :: KTAG 
      INTEGER(KIND=JWIM) :: NPRECR 
      INTEGER(KIND=JWIM) :: NPRECI 

!*     VARIABLE.     TYPE.   PURPOSE.
!      ---------     -----   --------
!      *IRANK*       INTEGER RANK OF THE CURRENT PROCESS (IN MPP MODE) 
!      *NPROC*       INTEGER TOTAL NUMBER OF PROCESSOR USED   
!      *NPREVIOUS*   INTEGER RANK OF PREVIOUS PROCESS
!      *NNEXT*       INTEGER RANK OF NEXT PROCESS
!      *NINF*        INTEGER SMALLEST GRID POINT INDEX USED BY THE PE
!      *NSUP*        INTEGER LARGEST GRID POINT INDEX USED BY THE PE
!      *MPMAXLENGTH* INTEGER MAXIMUM LENGTH OF SCALAR BLOCK MESSAGE
!      *KTAG*        INTEGER GLOBAL TAG FOR MESSAGE PASSING
!      *NPRECR*      INTEGER NUMBER OF BYTES TO REPRESENT REAL NUMBERS
!      *NPRECI*      INTEGER NUMBER OF BYTES TO REPRESENT INTEGERS

! ----------------------------------------------------------------------
      END MODULE YOWMPP
