      MODULE YOWMEAN

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
      USE YOWNEMOP, ONLY : NEMODP

      IMPLICIT NONE

!*    **  INTEGRATED PARAMETERS OF A BLOCK.

      REAL(KIND=JWRB), ALLOCATABLE :: EMEAN(:)
      REAL(KIND=JWRB), ALLOCATABLE :: FMEAN(:)
      REAL(KIND=JWRB), ALLOCATABLE :: NSWH(:)
      REAL(KIND=JWRB), ALLOCATABLE :: NMWP(:)

      REAL(KIND=JWRB), ALLOCATABLE :: ALTWH(:)
      REAL(KIND=JWRB), ALLOCATABLE :: CALTWH(:)
      REAL(KIND=JWRB), ALLOCATABLE :: RALTCOR(:)

      REAL(KIND=JWRB), ALLOCATABLE :: USTOKES(:)
      REAL(KIND=JWRB), ALLOCATABLE :: VSTOKES(:)

      REAL(KIND=JWRB), ALLOCATABLE :: PHIEPS(:)
      REAL(KIND=NEMODP),ALLOCATABLE :: NPHIEPS(:)
      REAL(KIND=JWRB), ALLOCATABLE :: PHIOCD(:)

      REAL(KIND=JWRB), ALLOCATABLE :: PHIAW(:)

      REAL(KIND=JWRB), ALLOCATABLE :: TAUOC(:)
      REAL(KIND=NEMODP),ALLOCATABLE :: NTAUOC(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TAUXD(:)
      REAL(KIND=JWRB), ALLOCATABLE :: TAUYD(:)
      REAL(KIND=JWRB), ALLOCATABLE :: TAUOCXD(:)
      REAL(KIND=JWRB), ALLOCATABLE :: TAUOCYD(:)

      REAL(KIND=JWRB), ALLOCATABLE :: STRNMS(:)

!*     VARIABLE.      TYPE.     PURPOSE.
!      ---------      -------   --------
!      *EMEAN*        REAL      TOTAL ENERGY.
!      *FMEAN*        REAL      MEAN FREQUENCY (1./MEAN PERIOD).
!      *NSWH*         REAL      SIGNIFICANT WAVE HEIGHT FOR NEMO
!      *NMWP*         REAL      MEAN WAVE PERIOD FOR NEMO

!      *ALTWH*        REAL      ALTIMETER WAVE HEIGHT 
!      *CALTWH*       REAL      CORRECTED ALTIMETER WAVE HEIGHT 
!      *RALTCOR*      REAL      ALTIMETER RANGE CORRECTION 

!      *USTOKES*      REAL      U-COMP SURFACE STOKES DRIFT.
!      *VSTOKES*      REAL      V-COMP SURFACE STOKES DRIFT.

!      *PHIEPS*       REAL      NORMALIZED ENERGY FLUX TO OCEAN.
!      *NPHIEPS*      REAL      COPY OF PHIEPS FOR NEMO
!      *PHIOCD*       REAL      DIMENSIONAL TURBULENT ENERGY FLUX INTO OCEAN.

!      *PHIAW*        REAL      NORMALIZED ENERGY FLUX FROM WIND TO WAVES.

!      *TAUOC*        REAL      NORMALIZED MOMENTUM FLUX INTO OCEAN.
!      *NTAUOC*       REAL      COPY OF TAUOC FOR NEMO.
!      *TAUXD*        REAL      DIMENSIONAL U-COMPONENT OF MOMENTUM FLUX FROM ATMOSPHERE.
!      *TAUYD*        REAL      DIMENSIONAL V-COMPONENT OF MOMENTUM FLUX FROM ATMOSPHERE.
!      *TAUOCXD*      REAL      DIMENSIONAL U-COMPONENT OF MOMENTUM FLUX INTO OCEAN.
!      *TAUOCYD*      REAL      DIMENSIONAL V-COMPONENT OF MOMENTUM FLUX INTO OCEAN.

!      *STRNMS*       REAL      MEAN SQUARE STRAIN INTO THE SEA ICE.

! ----------------------------------------------------------------------
      END MODULE YOWMEAN
