      MODULE YOWNEMOFLDS

      USE PARKIND1, ONLY : JPRO

      IMPLICIT NONE

!*     ** *NEMOFLDS* NEMO FIELDS FOR COUPLED RUNS

      SAVE
      REAL(KIND=JPRO), ALLOCATABLE :: NEMOSST(:)
      REAL(KIND=JPRO), ALLOCATABLE :: NEMOCICOVER(:)
      REAL(KIND=JPRO), ALLOCATABLE :: NEMOCITHICK(:)
      REAL(KIND=JPRO), ALLOCATABLE :: NEMOUCUR(:)
      REAL(KIND=JPRO), ALLOCATABLE :: NEMOVCUR(:)

      LOGICAL :: LNEMOCITHICK, LNEMOICEREST

!--------------------------------------------------------------------

!*    VARIABLE     TYPE      PURPOSE
!     --------     ----      -------
!     NEMOSST      REAL      NEMO SEA SURFACE TEMPERATURE
!     NEMOCICOVER  REAL      NEMO SEA ICE COVER.
!     NEMOCITHICK  REAL      NEMO SEA ICE THICKNESS.
!     NEMOUCUR     REAL      NEMO ZONAL CURRENT.
!     NEMOVCUR     REAL      NEMO MERIDIONAL CURRENT.
!     LNEMOCITHICK LOGICAL   SET TO TRUE IF SEA ICE THICKNESS IS 
!                            AVAILABLE FROM NEMO (E.G. LIM2 ACTIVE).
!--------------------------------------------------------------------
      END MODULE YOWNEMOFLDS
