      MODULE YOWNEMOP
      
      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!     NEMODP       INTEGER   FORCE DOUBLE PRECISION FOR VARIABLES PASSED
!                            TO NEMO
!      INTEGER, PARAMETER :: NEMODP = SELECTED_REAL_KIND(13,300)
      INTEGER(KIND=JWIM), PARAMETER :: NEMODP = JWRU

      END MODULE YOWNEMOP
