      MODULE YOWNEMOFLDS

      USE YOWNEMOP, ONLY : NEMODP

      IMPLICIT NONE

!*     ** *NEMOFLDS* NEMO FIELDS FOR COUPLED RUNS

      SAVE
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOSST(:) 
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOCICOVER(:) 
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOCITHICK(:) 
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOUCUR(:) 
      REAL(KIND=NEMODP), ALLOCATABLE :: NEMOVCUR(:) 

      LOGICAL :: LNEMOCITHICK, LNEMOICEREST

!--------------------------------------------------------------------

!*    VARIABLE     TYPE      PURPOSE
!     --------     ----      -------
!     NEMOSST      REAL      NEMO SEA SURFACE TEMPERATURE
!     NEMOCICOVER  REAL      NEMO SEA ICE COVER.
!     NEMOCITHICK  REAL      NEMO SEA ICE THICKNESS.
!     NEMOUCUR     REAL      NEMO ZONAL CURRENT.
!     NEMOVCUR     REAL      NEMO MERIDIONAL CURRENT.
!     LNEMOCITHICK LOGICAL   SET TO TRUE IF SEA ICE THICKNESS IS 
!                            AVAILABLE FROM NEMO (E.G. LIM2 ACTIVE).
!--------------------------------------------------------------------
      END MODULE YOWNEMOFLDS
