      MODULE YOWSPEC

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

      INTEGER(KIND=JWIM), ALLOCATABLE :: NSTART(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: NEND(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: NBLKS(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: NBLKE(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: KLENTOP(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: KLENBOT(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: NFROMPE(:) 
      INTEGER(KIND=JWIM) :: NFROMPEMAX
      INTEGER(KIND=JWIM), ALLOCATABLE :: NTOPE(:) 
      INTEGER(KIND=JWIM) :: NTOPEMAX
      INTEGER(KIND=JWIM), ALLOCATABLE :: NIJSTART(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJTOPE(:,:) 
      INTEGER(KIND=JWIM) :: NGBTOPE
      INTEGER(KIND=JWIM), ALLOCATABLE :: NTOPELST(:) 
      INTEGER(KIND=JWIM) :: NGBFROMPE
      INTEGER(KIND=JWIM), ALLOCATABLE :: NFROMPELST(:) 
      INTEGER(KIND=JWIM), ALLOCATABLE :: IJ2NEWIJ(:) 

      REAL(KIND=JWRB), ALLOCATABLE :: U10NEW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: U10OLD(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: THWNEW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: THWOLD(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: USNEW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: USOLD(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: Z0NEW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: Z0B(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: Z0OLD(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TAUW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: TAUWDIR(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: BETAOLD(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: ROAIRN(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: ROAIRO(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WSTARNEW(:) 
      REAL(KIND=JWRB), ALLOCATABLE :: WSTAROLD(:) 

      REAL(KIND=JWRB), ALLOCATABLE, DIMENSION(:,:,:) :: FL1

!     *NSTART*    INDEX OF THE FIRST POINT OF THE COMPUTATION SUB GRID DOMAIN
!     *NEND*      INDEX OF THE LAST POINT OF THE COMPUTATION SUB GRID DOMAIN
!     *NBLKS*     INDEX OF THE FIRST POINT OF THE SUB GRID DOMAIN (only local points)
!     *NBLKE*     INDEX OF THE LAST POINT OF THE SUB GRID DOMAIN (only local points)
!     *KLENTOP*   LENGTH OF THE MESSAGE SENT BY THE NEXT
!                 SUB GRID DOMAIN (IN GRID POINT UNIT)
!     *KLENBOT*   LENGTH OF THE MESSAGE SENT BY THE PREVIOUS
!                 SUB GRID DOMAIN (IN GRID POINT UNIT)
!     *NFROMPE*   INDICATES HOW MANY HALO POINTS THE LOCAL PE NEEDS
!                 TO GET FROM THE OTHER PE'S.
!     *NFROMPEMAX*MAXIMUM OF NFROMPE
!     *NTOPE*     INDICATES HOW MANY HALO POINTS THE LOCAL PE NEEDS
!                 TO SEND TO THE OTHER PE'S.
!     *NTOPEMAX*  MAXIMUM OF NTOPE
!     *NIJSTART*  INDEX OF THE FIRST HALO POINT FROM A GIVEN PE
!                 IN THE LOCAL HALO BUFFERS WHICH PADS BOTH ENDS OF
!                 THE LOCAL GRID POINT 1-D ARRAY
!     *IJTOPE*    TELLS THE LOCAL PE THE INDEX OF WHICH POINTS IT NEEDS
!                 TO SEND TO THE OTHER PE'S.
!     *NGBTOPE*   TOTAL NUMBER OF PE's TO WHICH INFORMATION WILL BE
!                 SENT FROM THE LOCAL PE VIA MESSAGE PASSING
!     *NTOPELST*  LIST OF THE PE'S TO WHICH INFORMATION WILL BE SENT
!     *NGBFROMPE* TOTAL NUMBER OF PE's FROM WHICH INFORMATION WILL BE
!                 RECEIVED TO THE LOCAL PE VIA MESSAGE PASSING
!     *NFROMPELST*LIST OF THE PE'S FROM WHICH INFORMATION WILL BE
!                 RECEIVED
!     *IJ2NEWIJ*  TRANSFORMS THE OLD INDEX IJ INTO THE NEW IJ AS
!                 DETERMINED IN THE CASE OF 2-D DECOMPOSITION
!                 (SEE MPDECOMP).
!     *U10NEW*    NEW WIND SPEED IN M/S.
!     *U10OLD*    INTERMEDIATE STORAGE OF MODULUS OF WIND SPEED.
!     *THWNEW*    WIND DIRECTION IN RADIANS IN OCEANOGRAPHIC
!                 NOTATION (POINTING ANGLE OF WIND VECTOR,
!                 CLOCKWISE FROM NORTH).
!     *THWOLD*    INTERMEDIATE STORAGE OF WIND DIRECTION 
!     *USNEW*     NEW FRICTION VELOCITY IN M/S.
!     *USOLD*     INTERMEDIATE STORAGE OF MODULUS OF FRICTION
!                 VELOCITY.
!     *Z0NEW*     ROUGHNESS LENGTH IN M.
!     *Z0B*       BACKGROUND ROUGHNESS LENGTH IN M.
!     *Z0OLD*     INTERMEDIATE STORAGE OF ROUGHNESS LENGTH IN M.
!     *TAUW*      WAVE STRESS MAGNITUDE IN (M/S)**2
!     *TAUWDIR*   WAVE STRESS DIRECTION
!     *BETAOLD*   CHARNOCK COEFFICIENT AT THE BEGINNING OF TIME STEP
!     *FL1*       FREQUENCY SPECTRUM.
! ----------------------------------------------------------------------

      END MODULE YOWSPEC 
