      MODULE YOWSHAL

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *SHALLOW*   SHALLOW WATER TABLES.

      INTEGER(KIND=JWIM)              :: NDEPTH
      INTEGER(KIND=JWIM), ALLOCATABLE :: INDEP(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IODP(:)
      INTEGER(KIND=JWIM), ALLOCATABLE :: IOBND(:)

      REAL(KIND=JWRB), PARAMETER   :: GAM_B_J = 0.8_JWRB
      REAL(KIND=JWRB), PARAMETER   :: BATHYMAX = 999.0_JWRB
      REAL(KIND=JWRB), PARAMETER   :: XKDMIN = 0.75_JWRB 

      REAL(KIND=JWRB)              :: DEPTHA
      REAL(KIND=JWRB)              :: DEPTHD
      REAL(KIND=JWRB)              :: TOOSHALLOW
      REAL(KIND=JWRB), ALLOCATABLE :: DEPTH(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: TCGOND(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: CINV(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: TFAK(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: TSIHKD(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: TFAC_ST(:,:)
      REAL(KIND=JWRB), ALLOCATABLE :: EMAXDPT(:)

!*     VARIABLE.   TYPE.     PURPOSE.
!      ---------   -------   --------
!      *NDEPTH*    INTEGER   LENGTH OF SHALLOW WATER TABLES (see MTABS).
!      *INDEP*     INTEGER   DEPTH INDEX FOR A BLOCK.
!      *IODP*      INTEGER   : 0 OVER LAND, 1 OVER SEA.
!      *IOBND*     INTEGER   : 0 OVER BOUNDARY POINTS, 1 OTHERWISE.
!      *GAM_B_J    REAL      FACTIO OF THE DEPTH THAT DETERMINES THE MAXIMUM SIGNIFICANT WAVE HEIGHT ALLOWED
!      *BATHYMAX*  REAL      MAXIMUM DEPTH, ASSUMED TO CORRESPOND TO DEEP WATER CONDITIONS
!      *XKDMIN*    REAL      MINIMUM VALUE FOR K*DEPTH IN NON-LINEAR EFFECT FOR FREAK WAVE SOFTWARE. 
!      *DEPTHA*    REAL      MINIMUM DEPTH FOR TABLES (METRES).
!      *TOOSHALLOW REAL      MINIMUM DEPTH THAT WILL BE ALLOWED
!                            USED TO POINT TO LAND POINTS
!      *DEPTHD*    REAL      DEPTH INCREMENT (METRES).
!      *DEPTH*     REAL      WATER DEPTH IN METRES.
!      *TCGOND*    REAL      SHALLOW WATER GROUP VELOCITY TABLE.
!      *CINV*      REAL      RECIPROCAL OF THE PHASE VELOCITY (1/c)
!      *TFAK*      REAL      WAVE NUMBER TABLE.
!      *TSIHKD*    REAL      TABLE FOR OMEGA/SINH(2KD).
!      *TFAC_ST*   REAL      TABLE FOR 2*G*K**2/(OMEGA*TANH(2KD)).
!      *EMAXDPT*   REAL      MAXIMUM WAVE VARIANCE ALLOWED FOR A GIVEN DEPTH
!                            EMAXDPT=0.0625*(GAM_B_J*DEPTH)**2


! ----------------------------------------------------------------------
      END MODULE YOWSHAL
