      MODULE YOWUNIT

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    **  *UNITS* - INPUT / OUTPUT UNITS.


!!!! some are totally obsolete !!! will need to be cleaned

      INTEGER(KIND=JWIM), PARAMETER :: IREADG=1
      INTEGER(KIND=JWIM), PARAMETER :: NPROPAGS=2
      INTEGER(KIND=JWIM) :: IU02
      INTEGER(KIND=JWIM) :: IU07
      INTEGER(KIND=JWIM), DIMENSION(0:NPROPAGS) :: IU08
      INTEGER(KIND=JWIM) :: IU11
      INTEGER(KIND=JWIM) :: IU12
      INTEGER(KIND=JWIM) :: IU13
      INTEGER(KIND=JWIM) :: IU14
      INTEGER(KIND=JWIM) :: IU15
      INTEGER(KIND=JWIM) :: IU16
      INTEGER(KIND=JWIM) :: IU17
      INTEGER(KIND=JWIM) :: IU18
      INTEGER(KIND=JWIM), ALLOCATABLE :: IU19(:)
      INTEGER(KIND=JWIM) :: IU20
      INTEGER(KIND=JWIM) :: IU22
      INTEGER(KIND=JWIM) :: IU23
      INTEGER(KIND=JWIM) :: IU24
      INTEGER(KIND=JWIM) :: IU27
      INTEGER(KIND=JWIM) :: IU28
      INTEGER(KIND=JWIM) :: IUVELO
      INTEGER(KIND=JWIM) :: IU04
      INTEGER(KIND=JWIM) :: IU30
      INTEGER(KIND=JWIM) :: IU31
      INTEGER(KIND=JWIM) :: IU32
      INTEGER(KIND=JWIM) :: IU33
      INTEGER(KIND=JWIM) :: IU34
      INTEGER(KIND=JWIM) :: IU35
      INTEGER(KIND=JWIM) :: IU36
      INTEGER(KIND=JWIM) :: IU37
      INTEGER(KIND=JWIM) :: IU38
      INTEGER(KIND=JWIM) :: IU70
      INTEGER(KIND=JWIM) :: IU71

      LOGICAL :: LWVWAMINIT=.TRUE.

!      *IREADG*- PROCESSOR NUMBER DOING THE READING.
!      *IU02*  - LOGICAL UNIT FOR INPUT OF BOUDARY VALUES FROM A
!                PREVIOUS COARSE GRID IF THIS A FINE GRID RUN.
!      *IU08*  - LOGICAL UNITS FOR INPUT OF  UBUF
!                (OUTPUT OF PREPROC).
!      *IU11*  - LOGICAL UNIT FOR INPUT OF SPECTRA AT ALL GRID
!                POINTS. EACH PROPAGATION TIMESTEP THE FILES
!                CONNECTED TO IU11 AND IU12 ARE INTERCHANGED.
!      *IU12*  - LOGICAL UNIT FOR OUTPUT (SEE IU11).
!      *IU13*  - LOGICAL UNIT FOR INPUT OF SPECTRA ON LAST LATUTUDE
!                OF A BLOCK. SPECTRA ARE SAVED FROM THE SECOND
!                LATITUDE OF THE NEXT BLOCK.
!                EACH PROPAGATION TIMESTEP THE FILES CONNECTED TO
!                IU14 AND IU13 ARE INTERCHANGED.
!      *IU14*  - LOGICAL UNIT FOR OUTPUT (SEE IU13).
!      *IU15*  - LOGICAL UNIT FOR OUTPUT OF LAST WINDFIELDS FOR
!                RESTART.
!      *IU16*  - LOGICAL UNIT FOR INPUT/OUTPUT OF  REFDOT
!                (SEE SUBS PROPDOT AND DOTDC)
!      *IU17*  - LOGICAL UNIT FOR BLOCK WINDINPUT (SEE SUB. IMPLSCH)
!      *IU18*  - LOGICAL UNIT FOR BLOCK WINDINPUT (SEE SUB. IMPLSCH)
!      *IU19*  - LOGICAL UNIT FOR OUTPUT OF OF BOUNDARY VALUES IF
!                THIS IS A FINE GRID RUN.
!      *IU20*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF THE TOTAL SPECTRUM (FIRST GUESS).
!      *IU22*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF THE TOTAL SPECTRUM (ANALYSIS).
!      *IU23*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF SWELL, WIND WAVES AND 3 TRAINS (ANALYSIS).
!      *IU24*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF AG WAVE TRAIN SEPERATION (FIRST GUESS).
!      *IU25*  - LOGICAL UNIT FOR OUTPUT OF SPECTRA AT CERTAIN
!                GRID POINTS (FIRST GUESS).
!      *IU26*  - LOGICAL UNIT FOR OUTPUT OF SWELL SPECTRA AT
!                CERTAIN GRID POINTS (FIRST GUESS).
!      *IU27*  - LOGICAL UNIT FOR OUTPUT OF SPECTRA AT CERTAIN
!                GRID POINTS (ANALYSIS).
!      *IU28*  - LOGICAL UNIT FOR OUTPUT OF SWELL SPECTRA AT
!                CERTAIN GRID POINTS (ANALYSIS).
!      *IU70*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF AG WAVE TRAIN SEPERATION (ANALYSIS).
!      *IUVELO*- OUTPUT UNIT FOR BLOCKED WIND FIELDS.
!      *IU04*  - INPUT AND OUTPUT UNIT OF WAMINFO FILE.

!                LOGICAL UNITS FOR GRIBBED OUTPUT:
!      *IU30*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                  OF THE TOTAL SPECTRUM (FIRST GUESS).
!      *IU31*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF SWELL AND WIND WAVES (FIRST GUESS).
!      *IU32*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF THE TOTAL SPECTRUM (ANALYSIS).
!      *IU33*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF SWELL AND WIND WAVES (ANALYSIS).
!      *IU34*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF AG WAVE TRAIN SEPERATION (FIRST GUESS).
!      *IU35*  - LOGICAL UNIT FOR OUTPUT OF SPECTRA AT CERTAIN
!                GRID POINTS (FIRST GUESS).
!      *IU36*  - LOGICAL UNIT FOR OUTPUT OF SWELL SPECTRA AT
!                CERTAIN GRID POINTS (FIRST GUESS).
!      *IU37*  - LOGICAL UNIT FOR OUTPUT OF SPECTRA AT CERTAIN
!                GRID POINTS (ANALYSIS).
!      *IU38*  - LOGICAL UNIT FOR OUTPUT OF SWELL SPECTRA AT
!                CERTAIN GRID POINTS (ANALYSIS).
!      *IU71*  - LOGICAL UNIT FOR OUTPUT OF INTEGRATED PARAMETERS
!                OF AG WAVE TRAIN SEPERATION (ANALYSIS).
!      *LWVWAMINIT* - TRUE IF LWVWAMINIT HAS TO BE CALLED.
! ----------------------------------------------------------------------

      END MODULE YOWUNIT
