! THE PURPOSE OF THIS DUMMY SUBROUTINE PACKAGE IS TO SUPPLEMEMT
! THE COMPILER WITH A FICTIVE DEFINITION OF SUBROUTINES
! FOUND IN THE WAM CODE (IE: THERE IS A CALL TO IT) BUT THEIR 
! DEFINITION RELY ON DIFFERENT LIBRARIES THAT ARE IN USE AT ECMWF
! BUT ARE NOT NEEDED TO RUN WAM WITHOUT DATA ASSIMILATION
! OR COULD BE REPLACED BY A SIMILAR ROUTINE.

! JEAN BIDLOT  ECMWF NOVEMBER 1995

! -----------------------------------------------------------------
!
       SUBROUTINE WAMASSI 
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '              SUBROUTINE WAMASSI !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF NO DATA'
       WRITE(*,*) 'ASSIMILATION IS DONE !!!'
       CALL ABORT1
       RETURN
       END SUBROUTINE WAMASSI

       SUBROUTINE SARINVERT 
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '              SUBROUTINE SARINVERT !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED BECAUSE'
       WRITE(*,*) 'THE SAR INVERSION SOFTWARE WAS NOT PROVIDED !!!'
       CALL ABORT1
       RETURN
       END SUBROUTINE SARINVERT

!       SUBROUTINE WAM_SYMINV 
!       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
!       WRITE(*,*) '              SUBROUTINE WAM_SYMINV !!!'
!       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
!       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF NO DATA'
!       WRITE(*,*) 'ASSIMILATION IS DONE !!!'
!       WRITE(*,*) 'THIS ROUTINE IS PART OF THE ECMWF LIBRARY :'
!       WRITE(*,*) 'EMOSLIB OR ECLIB '
!       CALL ABORT1
!       RETURN
!       END SUBROUTINE WAM_SYMINV

       SUBROUTINE SYMINV 
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '              SUBROUTINE SYMINV !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF NO DATA'
       WRITE(*,*) 'ASSIMILATION IS DONE !!!'
       WRITE(*,*) 'THIS ROUTINE IS PART OF THE ECMWF LIBRARY :'
       WRITE(*,*) 'EMOSLIB OR ECLIB '
       CALL ABORT1
       RETURN
       END SUBROUTINE SYMINV

       SUBROUTINE DGELSS
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '              SUBROUTINE DGELSS !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF NO DATA'
       WRITE(*,*) 'ASSIMILATION IS DONE !!!'
       WRITE(*,*) 'THIS ROUTINE IS PART OF THE LAPACK LIBRARY'
       WRITE(*,*) 'WHICH IS NOT PROVIDED HERE !'
       CALL ABORT1
       RETURN
       END SUBROUTINE DGELSS

       SUBROUTINE C06FUF
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '              SUBROUTINE C06FUF !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF NO DATA'
       WRITE(*,*) 'ASSIMILATION IS DONE !!!'
       WRITE(*,*) 'THIS ROUTINE IS PART OF THE NAG LIBRARY'
       WRITE(*,*) 'WHICH IS NOT PROVIDED HERE !'
       CALL ABORT1
       RETURN
       END SUBROUTINE C06FUF

       SUBROUTINE NEMOGCMCOUP_WAM_COUPINIT
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '           SUBROUTINE NEMOGCMCOUP_WAM_COUPINIT !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF '
       WRITE(*,*) 'CUPLING TO NEMO IS DONE !!!'
       WRITE(*,*) 'THIS ROUTINE IS PART OF THE NEMO LIBRARY'
       WRITE(*,*) 'WHICH IS NOT PROVIDED HERE !'
       CALL ABORT1
       RETURN
       END SUBROUTINE NEMOGCMCOUP_WAM_COUPINIT

       SUBROUTINE NEMOGCMCOUP_WAM_UPDATE
       WRITE(*,*) 'FATAL ERROR : ATTEMPT TO USE THE DUMMY DEFINITION OF'
       WRITE(*,*) '           SUBROUTINE NEMOGCMCOUP_WAM_UPDATE !!!'
       WRITE(*,*) 'THE ROUTINE WAS REPLACED BY A DUMMY'
       WRITE(*,*) 'DEFINITION AS IT SHOULD NOT BE USED IF '
       WRITE(*,*) 'CUPLING TO NEMO IS DONE !!!'
       WRITE(*,*) 'THIS ROUTINE IS PART OF THE NEMO LIBRARY'
       WRITE(*,*) 'WHICH IS NOT PROVIDED HERE !'
       CALL ABORT1
       RETURN
       END SUBROUTINE NEMOGCMCOUP_WAM_UPDATE
