      SUBROUTINE OUTBLOCK (IJS, IJL, KIJS, KIJL, MIJ,                 &
     &                     GFL, GXLLWS, GVG,                          &
     &                     DEPTH,
     &                     GBOUT)
! ----------------------------------------------------------------------

!**** *OUTBLOCK* - MODEL OUTPUT FROM BLOCK TO FILE, PRINTER AND COMMON.


!*    PURPOSE.
!     --------

!       PREPARE OUTPUT INTEGRATED PARAMETERS FOR ONE BLOCk OF DATA


!**   INTERFACE.
!     ----------
!      *CALL*OUTBLOCK (IJS, IJL, KIJS, KIJL, MIJ,
!     &                GFL, GXLLWS, GVG,
!     &                DEPTH,
!     &                GBOUT)
!      *IJS:IJL*- 1st DIMEMSION of GFL, GXLLWS, GVG, GBOUT
!      *KIJS*   - INDEX OF FIRST LOCAL GRIDPOINT
!      *KIJL*   - INDEX OF LAST LOCAL GRIDPOINT
!      *MIJ*    - LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE.
!      *GFL*    - INPUT SPECTRUM.
!      *GXLLWS* - WINDSEA MASK FROM INPUT SOURCE TERM
!      *GVG*    - GROUP SPEED
!      *DEPTH*  - DEPTH
!      *GBOUT*  - OUTPUT PARAMETER BUFFER

!     EXTERNALS.
!     ----------

!       *FEMEAN*    - COMPUTATION OF MEAN FREQUENCY AT EACH GRID POINT.
!       *INTPOL*    - MAP SPECTRUM FROM SIGMA TO OMEGA SPACE.
!       *OUTERS*    - OUTPUT OF SATELLITE COLOCATION SPECTRA.
!       *SEMEAN*    - COMPUTATION OF TOTAL ENERGY AT EACH GRID POINT.
!       *SEPWISW*   - SEPARATION OF WINDSEA AND SWELL.
!       *SEP3TR*    - SEPARATION OF WAVE SPECTRA INTO 3 WAVE TRAINS
!       *STHQ*      - COMPUTATION OF MEAN WAVE DIRECTION AT EACH
!                     GRID POINT.
!       *MWP1*      - COMPUTATION OF MEAN PERIOD (1) AT EACH GRID POINT.
!       *MWP2*      - COMPUTATION OF MEAN PERIOD (2) AT EACH GRID POINT.
!       *WDIRSPREAD*- COMPUTATION OF MEAN DIRECTIONAL SPREAD AT EACH 
!                     GRID POINT. 
!       *KURTOSIS*  - COMPUTATION OF THE SURFACE ELEVATION KURTOSIS, 
!                     THE BEJAMIN-FEIR INDEX, THE SPECTRAL PEAKEDNESS 
!                     FACTOR AND THE MAXIMUM WAVE HEIGHT.
!       *STOKESDRIFT*  - COMPUTATION OF THE STOKES DRIFT VECTOR. 
!   
!     METHOD.
!     -------

!       NONE.

!     REFERENCE.
!     ----------

!       NONE.

! ----------------------------------------------------------------------
      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      USE YOWCOUT  , ONLY : NTRAIN   ,IPFGTBL  ,LSECONDORDER,           &
     &            NIPRMOUT, ITOBOUT
      USE YOWCOUP  , ONLY : LWNEMOCOUSTRN
      USE YOWCURR  , ONLY : U, V
      USE YOWFRED  , ONLY : FR       ,DFIM     ,DELTH    ,COSTH    ,SINTH, XKMSS_CUTOFF
      USE YOWICE   , ONLY : CICOVER  ,CITHICK
      USE YOWMEAN  , ONLY : ALTWH    ,CALTWH   ,RALTCOR  ,              &
     &            USTOKES  ,VSTOKES  ,STRNMS   ,                        &
     &            PHIEPS   ,PHIAW    ,TAUOC    ,TAUXD    ,TAUYD     ,   &
     &            TAUOCXD  ,TAUOCYD  ,PHIOCD

      USE YOWNEMOFLDS,ONLY: NEMOSST, NEMOCICOVER, NEMOCITHICK,          &
     &                      NEMOUCUR, NEMOVCUR, LNEMOCITHICK
      USE YOWSPEC  , ONLY : TAUW     ,U10NEW   ,THWNEW   ,USNEW    ,    &
     &            ROAIRN   ,ZIDLNEW
      USE YOWPARAM , ONLY : NANG     ,NFRE
      USE YOWPCONS , ONLY : ZMISS    ,DEG      ,EPSUS    ,EPSU10, G, ZPI
      USE YOWSHAL,   ONLY : IODP
      USE YOWSTAT  , ONLY : IREFRA

      USE YOMHOOK  , ONLY : LHOOK,   DR_HOOK

! ----------------------------------------------------------------------

      IMPLICIT NONE
#include "cal_second_order_spec.intfb.h"
#include "cimsstrn.intfb.h"
#include "femean.intfb.h"
#include "intpol.intfb.h"
#include "kurtosis.intfb.h"
#include "meansqs.intfb.h"
#include "mwp1.intfb.h"
#include "mwp2.intfb.h"
#include "outsetwmask.intfb.h"
#include "dominant_period.intfb.h"
#include "se10mean.intfb.h"
#include "sebtmean.intfb.h"
#include "sepwisw.intfb.h"
#include "sthq.intfb.h"
#include "wdirspread.intfb.h"
#include "weflux.intfb.h"
#include "halphap.intfb.h"
#include "alphap_tail.intfb.h"

      INTEGER(KIND=JWIM), INTENT(IN) :: IJS, IJL, KIJS, KIJL
      INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: MIJ

      REAL(KIND=JWRB), DIMENSION(IJS:IJL,NANG,NFRE), INTENT(IN) :: GFL, GXLLWS
      REAL(KIND=JWRB), DIMENSION(IJS:IJL,NFRE), INTENT(IN) :: GVG

      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH 

      REAL(KIND=JWRB), DIMENSION(IJS:IJL,NIPRMOUT), INTENT(OUT) :: GBOUT



      INTEGER(KIND=JWIM), PARAMETER :: NTEWH=6
      INTEGER(KIND=JWIM) :: IJ, K, M, ITG, IR, ITR, IH
      INTEGER(KIND=JWIM) :: IRA
      
      REAL(KIND=JWRB) :: SIG
      REAL(KIND=JWRB) :: GOZPI 
      REAL(KIND=JWRB) :: XMODEL_CUTOFF
      REAL(KIND=JWRB) :: ZHOOK_HANDLE
      REAL(KIND=JWRB), DIMENSION(0:NTEWH) :: TEWH
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: EM, FM, DP
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: C3, C4, BF, QP, HMAX, TMAX
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: ETA_M, R, XNSLC, SIG_TH, EPS
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: FLD1, FLD2
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: ESWELL ,FSWELL ,THSWELL, P1SWELL, P2SWELL, SPRDSWELL
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: ESEA   ,FSEA   ,THWISEA, P1SEA  , P2SEA  , SPRDSEA
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL) :: HALP, WAVEAGESEA
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NTRAIN) :: EMTRAIN
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NTRAIN) :: THTRAIN, PMTRAIN

!     *FL2ND*  SPECTRUM with second order effect added if LSECONDORDER is true .
!            and in the absolute frame of reference if currents are used 
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE) :: FL2ND

      LOGICAL :: LLPEAKF

      DATA TEWH /10._JWRB,12._JWRB,14._JWRB,17._JWRB,21._JWRB,25._JWRB,30._JWRB/

! ----------------------------------------------------------------------

      IF (LHOOK) CALL DR_HOOK('OUTBLOCK',0,ZHOOK_HANDLE)

!
!*    1. COMPUTE MEAN PARAMETERS.
!        ------------------------

!     PREPARE THE WAVE SPECTRA THAt SHOULD BE USED FOR OUTPUT

      LLPEAKF = .FALSE.

      IRA=1
      SIG = 1._JWRB
      WAVEAGESEA(:)=ZMISS
      GOZPI=G/ZPI

      IF (IREFRA.EQ.2 .OR. IREFRA.EQ.3) THEN
        CALL INTPOL (GFL, FL2ND, IJS, IJL, KIJS, KIJL, IRA)
      ELSE
        FL2ND(KIJS:KIJL,:,:) = GFL(KIJS:KIJL,:,:)
      ENDIF
      IF(LSECONDORDER) CALL CAL_SECOND_ORDER_SPEC(FL2ND,KIJS,KIJL,DEPTH,SIG)


!     COMPUTE MEAN PARAMETERS
      CALL FEMEAN (FL2ND, KIJS, KIJL, KIJS, KIJL, EM, FM)

      CALL DOMINANT_PERIOD (GFL, IJS, IJL, KIJS, KIJL, DP)

      CALL KURTOSIS(GFL, IJS, IJL, KIJS, KIJL,                          &
     &              DEPTH,                                              &
     &              C3, C4, BF, QP, HMAX, TMAX,                         &
     &              ETA_M, R, XNSLC, SIG_TH, EPS)

!     WIND/SWELL PARAMETERS
      CALL SEPWISW (IJS, IJL, KIJS, KIJL, MIJ, GFL, GXLLWS,               &
     &              USNEW(KIJS), U10NEW(KIJS), THWNEW(KIJS),              &
     &              ESWELL, FSWELL, THSWELL, P1SWELL, P2SWELL, SPRDSWELL, &
     &              ESEA, FSEA, THWISEA, P1SEA, P2SEA, SPRDSEA,           &
     &              EMTRAIN, THTRAIN, PMTRAIN)


!     LOAD THE OUTPUT BUFFER:
      IR=0

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       SIGNIFICANT WAVE HEIGHT CONVERSION
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=4._JWRB*SQRT(MAX(EM(KIJS:KIJL),0._JWRB))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        ITG=ITOBOUT(IR)
        CALL STHQ (FL2ND, KIJS, KIJL, GGBOUT(KIJS,ITG))
!       CONVERT DIRECTIONS TO DEGREES AND METEOROLOGICAL CONVENTION
        GGBOUT(KIJS:KIJL,ITG)=MOD(DEG*GGBOUT(KIJS:KIJL,ITG)+180._JWRB,360._JWRB)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERSION TO PERIOD
        DO IJ=KIJS,KIJL
          IF(FM(IJ).GT.0._JWRB) THEN
            GBOUT(IJ,ITOBOUT(IR))=1._JWRB/FM(IJ)
          ELSE
            GBOUT(IJ,ITOBOUT(IR))=ZMISS
          ENDIF
        ENDDO
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=USNEW(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!      CONVERT DIRECTIONS TO DEGREES AND METEOROLOGICAL CONVENTION
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=MOD(DEG*THWNEW(KIJS:KIJL)+180._JWRB,360._JWRB)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERSION TO PERIOD
        DO IJ=KIJS,KIJL
          IF(DP(IJ).GT.0.0_JWRB) THEN
            GBOUT(IJ,ITOBOUT(IR))=DP(IJ)
          ELSE
            GBOUT(IJ,ITOBOUT(IR))=ZMISS
          ENDIF
        ENDDO
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!!     if the numerical computation of TAU and CD changes, a similar
!!     modification has to be put in buildstress where the friction
!!     velocity is determined from U10 and CD.
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=MAX(USNEW(KIJS:KIJL)**2,EPSUS)/MAX(U10NEW(KIJS:KIJL)**2,EPSU10)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=TAUW(KIJS:KIJL)/MAX(USNEW(KIJS:KIJL)**2,EPSUS)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        CALL MEANSQS (XKMSS_CUTOFF, KIJS, KIJL, GFL, U10NEW(KIJS), USNEW(KIJS), THWNEW(KIJS), GGBOUT(KIJS,ITOBOUT(IR)))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=U10NEW(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       WINDSEA SIGNIFICANT WAVE HEIGHT CONVERSION
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=4._JWRB*SQRT(MAX(ESEA(KIJS:KIJL),0._JWRB))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       TOTAL SWELL SIGNIFICANT WAVE HEIGHT CONVERSION
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=4._JWRB*SQRT(MAX(ESWELL(KIJS:KIJL),0._JWRB))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERT DIRECTIONS TO DEGREES AND METEOROLOGICAL CONVENTION
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=MOD(DEG*THWISEA(KIJS:KIJL)+180._JWRB,360._JWRB)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERT DIRECTIONS TO DEGREES AND METEOROLOGICAL CONVENTION
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=MOD(DEG*THSWELL(KIJS:KIJL)+180._JWRB,360._JWRB)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERSION TO PERIOD
        DO IJ=KIJS,KIJL
          IF(FSEA(IJ).GT.0._JWRB) THEN
            GBOUT(IJ,ITOBOUT(IR))=1._JWRB/FSEA(IJ)
! for testing: estimate of wave age based on wind mean frequency
            WAVEAGESEA(IJ)=MIN(GOZPI/(0.9_JWRB*FSEA(IJ)*MAX(USNEW(IJ),EPSUS)),40.0_JWRB)
          ELSE
            GBOUT(IJ,ITOBOUT(IR))=ZMISS
! for testing: estimate of wave age based on wind mean frequency
            WAVEAGESEA(IJ)=ZMISS
          ENDIF
        ENDDO
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERSION TO PERIOD
        DO IJ=KIJS,KIJL
          IF(FSWELL(IJ).GT.0._JWRB) THEN
            GBOUT(IJ,ITOBOUT(IR))=1._JWRB/FSWELL(IJ)
          ELSE
            GBOUT(IJ,ITOBOUT(IR))=ZMISS
          ENDIF
        ENDDO
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT.ALLOCATED(ALTWH)) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=ALTWH(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT.ALLOCATED(CALTWH)) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=CALTWH(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT.ALLOCATED(RALTCOR)) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=RALTCOR(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        CALL MWP1 (FL2ND, KIJS, KIJL, GGBOUT(KIJS,ITOBOUT(IR)))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        CALL MWP2 (FL2ND, KIJS, KIJL, GGBOUT(KIJS,ITOBOUT(IR)))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        CALL WDIRSPREAD (FL2ND, KIJS, KIJL, EM, LLPEAKF, GGBOUT(KIJS,ITOBOUT(IR)))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=P1SEA(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=P1SWELL(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=P2SEA(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=P2SWELL(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=SPRDSEA(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=SPRDSWELL(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=C4(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=BF(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=QP(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=DEPTH(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=HMAX(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=TMAX(KIJS:KIJL)
      ENDIF

!     SURFACE STOKES DRIFT U and V
      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=USTOKES(KIJS:KIJL)
      ENDIF
      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=VSTOKES(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT.ALLOCATED(U)) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=0._JWRB
        ELSE
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=U(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT.ALLOCATED(V)) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=0._JWRB
        ELSE
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=V(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=PHIEPS(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=PHIAW(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GGBOUT(KIJS:KIJL,ITOBOUT(IR))=TAUOC(KIJS:KIJL)
      ENDIF

      DO ITR=1,NTRAIN
        IR=IR+1
        IF(IPFGTBL(IR).NE.0) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=4._JWRB*SQRT(MAX(EMTRAIN(KIJS:KIJL,ITR),0._JWRB))
        ENDIF

        IR=IR+1
        IF(IPFGTBL(IR).NE.0) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=MOD(DEG*THTRAIN(KIJS:KIJL,ITR)+180._JWRB,360._JWRB)
        ENDIF

        IR=IR+1
        IF(IPFGTBL(IR).NE.0) THEN
          GGBOUT(KIJS:KIJL,ITOBOUT(IR))=PMTRAIN(KIJS:KIJL,ITR)
        ENDIF
      ENDDO

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(LWNEMOCOUSTRN) THEN
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=STRNMS(KIJS:KIJL)
        ELSE
          CALL CIMSSTRN (GFL, KIJS, KIJL, GBOUT(KIJS,ITOBOUT(IR)))
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        CALL SE10MEAN (FL2ND, KIJS, KIJL, FLD1(KIJS))
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=4._JWRB*SQRT(MAX(FLD1(KIJS:KIJL),0._JWRB))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=ROAIRN(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZIDLNEW(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=CICOVER(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=CITHICK(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=C3(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT. ALLOCATED(NEMOSST)) THEN
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=NEMOSST(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT. ALLOCATED(NEMOCICOVER)) THEN
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=NEMOCICOVER(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF (LNEMOCITHICK) THEN
          IF(.NOT. ALLOCATED(NEMOCITHICK)) THEN
            GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
          ELSE
            GBOUT(KIJS:KIJL,ITOBOUT(IR))=NEMOCITHICK(KIJS:KIJL)
          ENDIF
        ELSE
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT. ALLOCATED(NEMOUCUR)) THEN
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=NEMOUCUR(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        IF(.NOT. ALLOCATED(NEMOVCUR)) THEN
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=ZMISS
        ELSE
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=NEMOVCUR(KIJS:KIJL)
        ENDIF
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0 .OR. IPFGTBL(IR+1).NE.0) THEN
           CALL WEFLUX (GFL, KIJS, KIJL,                                  &
     &                  NFRE, NANG, DFIM, DELTH,                        &
     &                  COSTH, SINTH, GVG,                           &
     &                  FLD1, FLD2)
      ENDIF
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=FLD1(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!       CONVERT DIRECTIONS TO DEGREES AND METEOROLOGICAL CONVENTION
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=MOD(DEG*FLD2(KIJS:KIJL)+180._JWRB,360._JWRB)
      ENDIF

      DO IH=1,NTEWH
        IR=IR+1
        IF(IPFGTBL(IR).NE.0) THEN
          CALL SEBTMEAN (FL2ND, KIJS, KIJL, TEWH(IH-1), TEWH(IH), GBOUT(KIJS,ITOBOUT(IR)))
!         SIGNIFICANT WAVE HEIGHT CONVERSION
          GBOUT(KIJS:KIJL,ITOBOUT(IR))=4._JWRB*SQRT(MAX(GBOUT(KIJS:KIJL,ITOBOUT(IR)),0._JWRB))
        ENDIF
      ENDDO

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=ETA_M(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=R(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=XNSLC(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=TAUXD(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=TAUYD(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=TAUOCXD(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=TAUOCYD(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!      !!! make the energy flux positive
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=MAX(-PHIOCD(KIJS:KIJL),0.0_JWRB)
      ENDIF


!     COMPUTE OUTPUT EXTRA FIELDS
!     add necessary code to compute the extra output fields
      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN

!!!for testing
        CALL HALPHAP(KIJS, KIJL, USNEW(KIJS), THWNEW(KIJS), GFL, HALP)
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=2.0_JWRB*HALP(KIJS:KIJL)

      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=WAVEAGESEA(KIJS:KIJL)
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
!!!for testing
        XMODEL_CUTOFF = (ZPI*FR(NFRE))**2/G
        CALL MEANSQS (XMODEL_CUTOFF, KIJS, KIJL, GFL, U10NEW(KIJS), USNEW(KIJS), THWNEW(KIJS), GBOUT(KIJS,ITOBOUT(IR)))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        CALL ALPHAP_TAIL(KIJS, KIJL, GFL, GBOUT(KIJS,ITOBOUT(IR)))
      ENDIF

      IR=IR+1
      IF(IPFGTBL(IR).NE.0) THEN
        GBOUT(KIJS:KIJL,ITOBOUT(IR))=5.0_JWRB
      ENDIF


!     APPLY SEA ICE MASK AND SEA MASK IF NECESSARY
      CALL OUTSETWMASK (IJS, IJL, KIJS, KIJL, IODP(KIJS), CICOVER(KIJS),GBOUT)

      IF (LHOOK) CALL DR_HOOK('OUTBLOCK',1,ZHOOK_HANDLE)

      END SUBROUTINE OUTBLOCK
