      SUBROUTINE WRITESTRESS(IJINF, IJSUP, NREAL, RFIELD, FILENAME, LRSTPARAL) 

! ----------------------------------------------------------------------
!     J. BIDLOT    ECMWF      APRIL 1997

!*    PURPOSE.
!     --------
!     WRITES THE RESTART WIND AND STRESS FIELDS TO FILE.

!**   INTERFACE.
!     ----------

!     CALL *WRITESTRESS*(IJINF, IJSUP, NREAL, RFIELD,
!                        FILENAME,LRSTPARAL)
!     *IJINF*    FIRST LOWER DIMENSION OF RFIELD 
!     *IJSUP*    FIRST UPPER DIMENSION OF RFIELD 
!     *NREAL*    NUMBER OF FIELDS IN RFIELD
!     *RFIELD*   REAL RESTART FIELDS
!     *FILENAME* FILENAME (INCLUDING PATH) OF TARGET FILE
!     *LRSTPARAL* LOGICAL, TRUE THEN WRITE IN PARALLEL

!     METHOD.
!     -------
!     WRITES ARRAYS TO FILE (FORTRAN WRITES).

!     THE OUTPUT IS WRITTEN AS UNFORMATTED BINARY TO FILENAME
!     IT IS IN A FORM THAT IS INDEPENDENT OF THE MODEL DECOMPOSITION.
!     IF LRSTPARAL IS FALSE


!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!     NONE
! ----------------------------------------------------------------------

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      USE YOWMPP   , ONLY : NPROC
      USE YOWPARAM , ONLY : LL1D
      USE YOWSTAT  , ONLY : CDTPRO
      USE YOWSPEC  , ONLY : IJ2NEWIJ
      USE YOWTEST  , ONLY : IU06
      USE YOWUNPOOL, ONLY : LLUNSTR
      USE YOWWIND  , ONLY : CDAWIFL  ,CDATEWO  ,CDATEFL

      USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK, JPHOOK

! ----------------------------------------------------------------------

      IMPLICIT NONE
#include "iwam_get_unit.intfb.h"
#include "unblkrord.intfb.h"

      INTEGER(KIND=JWIM), INTENT(IN) :: IJINF, IJSUP, NREAL
      REAL(KIND=JWRB),DIMENSION(IJINF:IJSUP,NREAL),INTENT(INOUT) :: RFIELD
      CHARACTER(LEN=296), INTENT(IN) :: FILENAME
      LOGICAL, INTENT(IN) :: LRSTPARAL

      INTEGER(KIND=JWIM) :: IFLD, IJ, IG
      INTEGER(KIND=JWIM) :: LFILE, IUNIT

      REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
      REAL(KIND=JWRB),DIMENSION(IJINF:IJSUP) :: RFIELD_G

      CHARACTER(LEN=1) :: MODE

! ----------------------------------------------------------------------

      IF (LHOOK) CALL DR_HOOK('WRITESTRESS',0,ZHOOK_HANDLE)

      LFILE=0
      IF (FILENAME /= ' ') LFILE=LEN_TRIM(FILENAME)
      IUNIT=IWAM_GET_UNIT(IU06, FILENAME(1:LFILE) , 'w', 'u', 0)

      WRITE(IUNIT) CDTPRO, CDATEWO, CDAWIFL, CDATEFL

      IF (LLUNSTR .AND. .NOT.LRSTPARAL) THEN
        DO IFLD=1,NREAL
          CALL UNBLKRORD(1,IJINF,IJSUP,1,1,1,1,RFIELD(1,IFLD),RFIELD_G(1))
          WRITE(IUNIT)(RFIELD_G(IJ),IJ=IJINF,IJSUP)
        ENDDO
      ELSEIF (LRSTPARAL .OR. LL1D .OR. NPROC == 1) THEN
        DO IFLD=1,NREAL
          WRITE(IUNIT)(RFIELD(IJ,IFLD),IJ=IJINF,IJSUP)
        ENDDO
      ELSE
        DO IFLD=1,NREAL
          WRITE(IUNIT) (RFIELD(IJ2NEWIJ(IJ),IFLD),IJ=IJINF,IJSUP)
        ENDDO
      ENDIF

      CLOSE(IUNIT)

      IF (LHOOK) CALL DR_HOOK('WRITESTRESS',1,ZHOOK_HANDLE)

      END SUBROUTINE WRITESTRESS
