      SUBROUTINE WVALLOC(LWCUR)

! ----------------------------------------------------------------------

!**** *WVALLOC* - WAVE MODEL ARRAY ALLOCATION

! ----------------------------------------------------------------------

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      USE YOWCOUP  , ONLY : LWCOU    ,LWCOU2W  ,LWFLUX
      USE YOWCURR  , ONLY : U        ,V
      USE YOWICE   , ONLY : CICOVER  ,CITHICK  ,CIWA
      USE YOWMEAN  , ONLY : EMEAN    ,FMEAN    ,THQ      ,PHIEPS   ,    &
     &                      PHIAW    ,TAUOC
      USE YOWMESPAS, ONLY : LMESSPASS
      USE YOWMPP   , ONLY : IRANK    ,NPROC    ,NPREVIOUS,NNEXT    ,    &
     &            NINF     ,NSUP     ,MPMAXLENGTH
      USE YOWPARAM , ONLY : NANG     ,NFRE     ,NBLO     ,NIBLO    ,    &
     &            LL1D
      USE YOWSPEC, ONLY : NSTART   ,NEND     ,                          &
     &            U10NEW   ,U10OLD   ,THWNEW   ,THWOLD   ,USNEW    ,    &
     &            USOLD    ,Z0NEW    ,Z0OLD    ,TAUW     ,BETAOLD  ,    &
     &            ROAIRN   ,ROAIRO   ,ZIDLNEW  ,ZIDLOLD  ,              &
     &            FL1      ,FL3
      USE YOWSTAT  , ONLY : IPROPAGS ,LSUBGRID ,IREFRA   ,IDELPRO
      USE YOWTEST  , ONLY : IU06
      USE YOWWIND, ONLY   : NXFF     ,NYFF     ,FIELDG_coupl
      USE MPL_MODULE
      USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

! ----------------------------------------------------------------------

      IMPLICIT NONE

      INTEGER(KIND=JWIM) :: NPR, MAXLEN

      REAL(KIND=JWRB) :: ZHOOK_HANDLE

      LOGICAL :: LWCUR

! ----------------------------------------------------------------------
 
      IF (LHOOK) CALL DR_HOOK('WVALLOC',0,ZHOOK_HANDLE)

!     1.  ALLOCATE NECESSARY ARRAYS
!         -------------------------

      IF(.NOT.ALLOCATED(U10OLD)) ALLOCATE(U10OLD(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(THWOLD)) ALLOCATE(THWOLD(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(USOLD)) ALLOCATE(USOLD(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(Z0OLD)) ALLOCATE(Z0OLD(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(TAUW)) ALLOCATE(TAUW(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(U10NEW)) ALLOCATE(U10NEW(NINF:NSUP))
      IF(.NOT.ALLOCATED(THWNEW)) ALLOCATE(THWNEW(NINF:NSUP))
      IF(.NOT.ALLOCATED(USNEW)) ALLOCATE(USNEW(NINF:NSUP))
      IF(.NOT.ALLOCATED(Z0NEW)) ALLOCATE(Z0NEW(NINF:NSUP))
      IF(.NOT.ALLOCATED(BETAOLD)) ALLOCATE(BETAOLD(NINF:NSUP))

#if defined MODEL_COUPLING_ATM_WAV || defined MODEL_COUPLING_OCN_WAV
      U10NEW = 0
      U10OLD = 0
#endif

      IF(.NOT.ALLOCATED(ROAIRO)) ALLOCATE(ROAIRO(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(ROAIRN)) ALLOCATE(ROAIRN(NINF:NSUP))
      IF(.NOT.ALLOCATED(ZIDLOLD)) ALLOCATE(ZIDLOLD(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(ZIDLNEW)) ALLOCATE(ZIDLNEW(NINF:NSUP))

      IF(.NOT.ALLOCATED(CICOVER)) ALLOCATE(CICOVER(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(CITHICK)) ALLOCATE(CITHICK(NINF:NSUP,NBLO))
      IF(.NOT.ALLOCATED(CIWA)) ALLOCATE(CIWA(NINF:NSUP,NFRE,NBLO))

      IF(.NOT.ALLOCATED(FL1)) ALLOCATE(FL1(NINF-1:NSUP,NANG,NFRE))
      IF(.NOT.ALLOCATED(FL3)) ALLOCATE(FL3(NINF-1:NSUP,NANG,NFRE))

      IF(.NOT.ALLOCATED(EMEAN)) ALLOCATE(EMEAN(NSTART(IRANK):NEND(IRANK)))
      IF(.NOT.ALLOCATED(FMEAN)) ALLOCATE(FMEAN(NSTART(IRANK):NEND(IRANK)))
      IF(.NOT.ALLOCATED(THQ)) ALLOCATE(THQ(NSTART(IRANK):NEND(IRANK)))

        IF(.NOT.ALLOCATED(PHIEPS)) THEN 
          ALLOCATE(PHIEPS(NSTART(IRANK):NEND(IRANK)))
          PHIEPS(:) = 0.0_JWRB
        ENDIF
        IF(.NOT.ALLOCATED(PHIAW)) THEN 
          ALLOCATE(PHIAW(NSTART(IRANK):NEND(IRANK)))
          PHIAW(:) = 0.0_JWRB
        ENDIF
        IF(.NOT.ALLOCATED(TAUOC)) THEN
          ALLOCATE(TAUOC(NSTART(IRANK):NEND(IRANK)))
          TAUOC(:) = 0.0_JWRB
        ENDIF

      IF ( (LWCOU .AND. LWCUR) .OR.                                     &
     &      IREFRA.EQ.2 .OR. IREFRA.EQ.3) THEN
        IF(.NOT.ALLOCATED(U)) THEN
          ALLOCATE(U(NINF-1:NSUP,NBLO))
          U=0.0_JWRB
        ENDIF
        IF(.NOT.ALLOCATED(V)) THEN
          ALLOCATE(V(NINF-1:NSUP,NBLO))
          V=0.0_JWRB
        ENDIF
      ENDIF

#if defined MODEL_COUPLING_ATM_WAV || defined MODEL_COUPLING_OCN_WAV || defined NETCDF_OUTPUT_WAM
      ALLOCATE(FIELDG_coupl(NXFF,NYFF))
#endif

      IF (LHOOK) CALL DR_HOOK('WVALLOC',1,ZHOOK_HANDLE)
 
      END SUBROUTINE WVALLOC
