! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE CPGRBOBSTRCT(M, K, NST, NEN, POBSTR)

!****  *CPGRBOBSTRCT* - COPY DECODED OBSTRUCTION COEFFICIENTS TO CORRESPONDING ARRAYS.
!                       OBSLAT, OBSLON, OBSCOR, OBSRLAT, OBSRLON

! -------------------------------------------------------------------

USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

USE YOWGRID  , ONLY : NPROMA_WAM
USE YOWMPP   , ONLY : IRANK
USE YOWPCONS , ONLY : ZMISS
USE YOWSTAT  , ONLY : IPROPAGS
USE YOWSPEC  , ONLY : NBLKS, NBLKE
USE YOWUBUF  , ONLY : OBSLAT, OBSLON, OBSCOR, OBSRLAT, OBSRLON,  &
                    & KTOIS, KTOOBSTRUCT

USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK

!----------------------------------------------------------------------

IMPLICIT NONE

INTEGER(KIND=JWIM), INTENT(IN)    :: M          !! FREQUENCY INDEX
INTEGER(KIND=JWIM), INTENT(IN)    :: K          !! DIRECTION INDEX FOR THE OBSTRUCTIONS INPUT
INTEGER(KIND=JWIM), INTENT(IN)    :: NST        !! NST:NEN POBSTR DIMEMSION 
INTEGER(KIND=JWIM), INTENT(IN)    :: NEN        !! 
REAL(KIND=JWRB), DIMENSION(NST:NEN), INTENT(IN) :: POBSTR !! DECODED ONSTRUCTION COEFFICIENT

INTEGER(KIND=JWIM) :: IJ, IS
INTEGER(KIND=JWIM) :: IOBSRT
INTEGER(KIND=JWIM) :: JKGLO, KIJS, KIJL

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPGRBOBSTRCT',0,ZHOOK_HANDLE)

IS = KTOIS(K,IPROPAGS)

IF ( IS > 0 ) THEN
  IOBSRT = KTOOBSTRUCT(K,IPROPAGS)
  SELECT CASE(IOBSRT)

  CASE(1)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ)
    DO JKGLO = NBLKS(IRANK), NBLKE(IRANK), NPROMA_WAM
      KIJS = JKGLO
      KIJL = MIN(KIJS+NPROMA_WAM-1, NBLKE(IRANK))
      DO IJ = KIJS, KIJL
        IF (POBSTR(IJ) /= ZMISS) THEN
          OBSLAT(IJ,M,IS) = POBSTR(IJ)
        ELSE
          OBSLAT(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(2)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ)
    DO JKGLO = NBLKS(IRANK), NBLKE(IRANK), NPROMA_WAM
      KIJS = JKGLO
      KIJL = MIN(KIJS+NPROMA_WAM-1, NBLKE(IRANK))
      DO IJ = KIJS, KIJL
        IF (POBSTR(IJ) /= ZMISS) THEN
          OBSLON(IJ,M,IS) = POBSTR(IJ)
        ELSE
          OBSLON(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(3)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ)
    DO JKGLO = NBLKS(IRANK), NBLKE(IRANK), NPROMA_WAM
      KIJS = JKGLO
      KIJL = MIN(KIJS+NPROMA_WAM-1, NBLKE(IRANK))
      DO IJ = KIJS, KIJL
        IF (POBSTR(IJ) /= ZMISS) THEN
          OBSRLAT(IJ,M,IS) = POBSTR(IJ)
        ELSE
          OBSRLAT(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(4)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ)
    DO JKGLO = NBLKS(IRANK), NBLKE(IRANK), NPROMA_WAM
      KIJS = JKGLO
      KIJL = MIN(KIJS+NPROMA_WAM-1, NBLKE(IRANK))
      DO IJ = KIJS, KIJL
        IF (POBSTR(IJ) /= ZMISS) THEN
          OBSRLON(IJ,M,IS) = POBSTR(IJ)
        ELSE
          OBSRLON(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  CASE(5)
    CALL GSTATS(1498,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO, KIJS, KIJL, IJ)
    DO JKGLO = NBLKS(IRANK), NBLKE(IRANK), NPROMA_WAM
      KIJS = JKGLO
      KIJL = MIN(KIJS+NPROMA_WAM-1, NBLKE(IRANK))
      DO IJ = KIJS, KIJL
        IF (POBSTR(IJ) /= ZMISS) THEN
          OBSCOR(IJ,M,IS) = POBSTR(IJ)
        ELSE
          OBSCOR(IJ,M,IS) = 1.0_JWRB
        ENDIF
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1498,1)

  END SELECT

ENDIF

IF (LHOOK) CALL DR_HOOK('CPGRBOBSTRCT',1,ZHOOK_HANDLE)

END SUBROUTINE CPGRBOBSTRCT
