MODULE PARKIND_WAVE
!
!     *** Define usual kinds ***
!
USE PARKIND1, ONLY : JPIM, JPRB, JPRD

IMPLICIT NONE
SAVE
PRIVATE
!
!     Integer Kinds
!     -------------
!
INTEGER, PARAMETER, PUBLIC :: JWIM = JPIM

!
!     Real Kinds
!     ----------
!
INTEGER, PARAMETER, PUBLIC :: JWRB = JPRB
INTEGER, PARAMETER, PUBLIC :: JWRU = JPRD
#ifdef PARKIND1_SINGLE_NEMO
INTEGER, PARAMETER, PUBLIC :: JWRO = SELECTED_REAL_KIND(6,37)
#else
INTEGER, PARAMETER, PUBLIC :: JWRO = SELECTED_REAL_KIND(13,300)
#endif
!

END MODULE PARKIND_WAVE
