      FUNCTION WAM_USER_CLOCK()

!   Returns system clock converted to micro-seconds

      USE PARKIND_WAVE, ONLY : JWIM, JWRU

      IMPLICIT NONE
      REAL(JWRU) :: WAM_USER_CLOCK
      INTEGER(KIND=JWIM) :: ICOUNT,ICOUNT_RATE,ICOUNT_MAX

      CALL SYSTEM_CLOCK(ICOUNT,ICOUNT_RATE,ICOUNT_MAX)
      IF(ICOUNT.NE.HUGE(0)) THEN
        WAM_USER_CLOCK = REAL(ICOUNT,JWRU) * 1.E6_JWRU /            &
     &                   REAL(ICOUNT_RATE,JWRU)
      ELSE
        WAM_USER_CLOCK = 0.0_JWRU
      ENDIF    

      RETURN
      END FUNCTION WAM_USER_CLOCK




