      MODULE YOWCARD

      USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU

      IMPLICIT NONE

!*    ** *WAMCARD* - TEXT OF THE WAMINFO FILE.

      INTEGER(KIND=JWIM), PARAMETER :: JPCL=17
      CHARACTER(LEN=72) :: CARD(JPCL) 
      END MODULE YOWCARD
