#! (C) Copyright 2022- ECMWF.
#!
#! This software is licensed under the terms of the Apache Licence Version 2.0
#! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#! In applying this licence, ECMWF does not waive the privileges and immunities
#! granted to it by virtue of its status as an intergovernmental organisation
#! nor does it submit to any jurisdiction.
#!
#!
#:mute
#:set f = io.open(os.path.dirname(_THIS_FILE_)+'/yowdrvtype_config.yml')
#:set ymlstring = f.read()
#:set input = ecwam_yaml_reader.yaml.safe_load(ymlstring)
#:set objtypes = input['objtypes']
#:set gpu_methods = ['SYNC_DEVICE_RDWR', 'SYNC_DEVICE_RDONLY', 'SYNC_HOST_RDWR', 'SYNC_HOST_RDONLY', 'GET_DEVICE_DATA_RDWR', 'GET_DEVICE_DATA_RDONLY', 'GET_DEVICE_DATA_WRONLY', 'GET_HOST_DATA_RDWR', 'GET_HOST_DATA_RDONLY', 'DELETE_DEVICE_DATA']
$:f.close()
#:endmute
#!
#!
MODULE YOWDRVTYPE

#:for obj in objtypes
   USE ${obj.upper()}$_TYPE_MOD, ONLY : ${obj.upper()}$, ALLOC, DEALLOC
#ifdef WAM_GPU
   USE ${obj.upper()}$_TYPE_MOD, ONLY : ${', '.join(gpu_methods)}$
#endif
#:endfor

END MODULE YOWDRVTYPE
