! (C) Copyright 1989- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE YOWFIELD_MOD

   USE PARKIND_WAVE, ONLY : JWRB, JWIM, JWRO
   USE FIELD_MODULE, ONLY : FIELD_3RB, FIELD_2IM, FIELD_2RB, FIELD_3IM, FIELD_4RB, FIELD_4IM, FIELD_2RD
   USE FIELD_FACTORY_MODULE, ONLY : FIELD_NEW, FIELD_DELETE
   IMPLICIT NONE

   TYPE FREQUENCY_FIELD
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: WAVNUM=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: CINV=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: CGROUP=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: XK2CG=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: OMOSNH2KD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: STOKFAC=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:), POINTER :: CIWA=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_WAVNUM=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_CINV=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_CGROUP=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_XK2CG=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_OMOSNH2KD=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_STOKFAC=>NULL()
          CLASS(FIELD_3RB), POINTER :: F_CIWA=>NULL()
      CONTAINS
         PROCEDURE :: INIT => FREQUENCY_FIELD_INIT
         PROCEDURE :: UPDATE_VIEW => FREQUENCY_UPDATE_VIEW
         PROCEDURE :: FINAL => FREQUENCY_FINAL
   END TYPE FREQUENCY_FIELD

   TYPE ENVIRONMENT_FIELD
          INTEGER(KIND=JWIM), DIMENSION(:), POINTER :: INDEP=>NULL()
          INTEGER(KIND=JWIM), DIMENSION(:), POINTER :: IODP=>NULL()
          INTEGER(KIND=JWIM), DIMENSION(:), POINTER :: IOBND=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: DELLAM1=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: COSPHM1=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: DEPTH=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: EMAXDPT=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: UCUR=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: VCUR=>NULL()
          CLASS(FIELD_2IM), POINTER :: F_INDEP=>NULL()
          CLASS(FIELD_2IM), POINTER :: F_IODP=>NULL()
          CLASS(FIELD_2IM), POINTER :: F_IOBND=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_DELLAM1=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_COSPHM1=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_DEPTH=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_EMAXDPT=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_UCUR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_VCUR=>NULL()
      CONTAINS
         PROCEDURE :: INIT => ENVIRONMENT_FIELD_INIT
         PROCEDURE :: UPDATE_VIEW => ENVIRONMENT_UPDATE_VIEW
         PROCEDURE :: FINAL => ENVIRONMENT_FINAL
   END TYPE ENVIRONMENT_FIELD

   TYPE FORCING_FIELDS_FIELD
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: UWND=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: VWND=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: AIRD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: WSTAR=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: CICOVER=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: CITHICK=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: LKFR=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: UCUR=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: VCUR=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: WSWAVE=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: WDWAVE=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: UFRIC=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUW=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUWDIR=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: Z0M=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: Z0B=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: CHRNCK=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: XLON=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: YLAT=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_UWND=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_VWND=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_AIRD=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_WSTAR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_CICOVER=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_CITHICK=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_LKFR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_UCUR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_VCUR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_WSWAVE=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_WDWAVE=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_UFRIC=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUW=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUWDIR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_Z0M=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_Z0B=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_CHRNCK=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_XLON=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_YLAT=>NULL()
      CONTAINS
         PROCEDURE :: INIT => FORCING_FIELDS_FIELD_INIT
         PROCEDURE :: UPDATE_VIEW => FORCING_FIELDS_UPDATE_VIEW
         PROCEDURE :: FINAL => FORCING_FIELDS_FINAL
   END TYPE FORCING_FIELDS_FIELD

   TYPE WAVE2OCEAN_FIELD
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NSWH=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NMWP=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NPHIEPS=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOPHIF=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NTAUOC=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOTAUX=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOTAUY=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOUSTOKES=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOVSTOKES=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOSTRN=>NULL()
          REAL(KIND=JWRO), DIMENSION(:), POINTER :: NEMOWSWAVE=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NSWH=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NMWP=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NPHIEPS=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOPHIF=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NTAUOC=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOTAUX=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOTAUY=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOUSTOKES=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOVSTOKES=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOSTRN=>NULL()
          CLASS(FIELD_2RD), POINTER :: F_NEMOWSWAVE=>NULL()
      CONTAINS
         PROCEDURE :: INIT => WAVE2OCEAN_FIELD_INIT
         PROCEDURE :: UPDATE_VIEW => WAVE2OCEAN_UPDATE_VIEW
         PROCEDURE :: FINAL => WAVE2OCEAN_FINAL
   END TYPE WAVE2OCEAN_FIELD

   TYPE INTGT_PARAM_FIELDS_FIELD
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: WSEMEAN=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: WSFMEAN=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: USTOKES=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: VSTOKES=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: PHIEPS=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: PHIOCD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: PHIAW=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUOC=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUXD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUYD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUOCXD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: TAUOCYD=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: STRNMS=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: ALTWH=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: CALTWH=>NULL()
          REAL(KIND=JWRB), DIMENSION(:), POINTER :: RALTCOR=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_WSEMEAN=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_WSFMEAN=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_USTOKES=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_VSTOKES=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_PHIEPS=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_PHIOCD=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_PHIAW=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUOC=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUXD=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUYD=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUOCXD=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_TAUOCYD=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_STRNMS=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_ALTWH=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_CALTWH=>NULL()
          CLASS(FIELD_2RB), POINTER :: F_RALTCOR=>NULL()
      CONTAINS
         PROCEDURE :: INIT => INTGT_PARAM_FIELDS_FIELD_INIT
         PROCEDURE :: UPDATE_VIEW => INTGT_PARAM_FIELDS_UPDATE_VIEW
         PROCEDURE :: FINAL => INTGT_PARAM_FIELDS_FINAL
   END TYPE INTGT_PARAM_FIELDS_FIELD

   TYPE SOURCE_CONTRIBS_FIELD
          REAL(KIND=JWRB), DIMENSION(:,:,:), POINTER :: FL1=>NULL()
          REAL(KIND=JWRB), DIMENSION(:,:,:), POINTER :: XLLWS=>NULL()
          INTEGER(KIND=JWIM), DIMENSION(:), POINTER :: MIJ=>NULL()
          CLASS(FIELD_4RB), POINTER :: F_FL1=>NULL()
          CLASS(FIELD_4RB), POINTER :: F_XLLWS=>NULL()
          CLASS(FIELD_2IM), POINTER :: F_MIJ=>NULL()
      CONTAINS
         PROCEDURE :: INIT => SOURCE_CONTRIBS_FIELD_INIT
         PROCEDURE :: UPDATE_VIEW => SOURCE_CONTRIBS_UPDATE_VIEW
         PROCEDURE :: FINAL => SOURCE_CONTRIBS_FINAL
   END TYPE SOURCE_CONTRIBS_FIELD

   CONTAINS
      SUBROUTINE FREQUENCY_FIELD_INIT(SELF, WAVNUM, CINV, CGROUP, XK2CG, OMOSNH2KD, STOKFAC, CIWA)
          CLASS(FREQUENCY_FIELD), INTENT(INOUT) :: SELF
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: WAVNUM
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: CINV
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: CGROUP
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: XK2CG
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: OMOSNH2KD
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: STOKFAC
          REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: CIWA

          IF(PRESENT(WAVNUM)) CALL FIELD_NEW(SELF%F_WAVNUM, DATA=WAVNUM)
          IF(PRESENT(CINV)) CALL FIELD_NEW(SELF%F_CINV, DATA=CINV)
          IF(PRESENT(CGROUP)) CALL FIELD_NEW(SELF%F_CGROUP, DATA=CGROUP)
          IF(PRESENT(XK2CG)) CALL FIELD_NEW(SELF%F_XK2CG, DATA=XK2CG)
          IF(PRESENT(OMOSNH2KD)) CALL FIELD_NEW(SELF%F_OMOSNH2KD, DATA=OMOSNH2KD)
          IF(PRESENT(STOKFAC)) CALL FIELD_NEW(SELF%F_STOKFAC, DATA=STOKFAC)
          IF(PRESENT(CIWA)) CALL FIELD_NEW(SELF%F_CIWA, DATA=CIWA)
      END SUBROUTINE FREQUENCY_FIELD_INIT

      SUBROUTINE FREQUENCY_UPDATE_VIEW(SELF, BLOCK_INDEX)
          CLASS(FREQUENCY_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), INTENT(IN) :: BLOCK_INDEX

          IF(ASSOCIATED(SELF%F_WAVNUM)) SELF%WAVNUM => SELF%F_WAVNUM%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CINV)) SELF%CINV => SELF%F_CINV%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CGROUP)) SELF%CGROUP => SELF%F_CGROUP%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_XK2CG)) SELF%XK2CG => SELF%F_XK2CG%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_OMOSNH2KD)) SELF%OMOSNH2KD => SELF%F_OMOSNH2KD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_STOKFAC)) SELF%STOKFAC => SELF%F_STOKFAC%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CIWA)) SELF%CIWA => SELF%F_CIWA%GET_VIEW(BLOCK_INDEX)
      END SUBROUTINE FREQUENCY_UPDATE_VIEW

      SUBROUTINE FREQUENCY_FINAL(SELF)
          CLASS(FREQUENCY_FIELD), INTENT(INOUT) :: SELF

          IF(ASSOCIATED(SELF%F_WAVNUM))THEN
              CALL FIELD_DELETE(SELF%F_WAVNUM)
          ENDIF
          IF(ASSOCIATED(SELF%F_CINV))THEN
              CALL FIELD_DELETE(SELF%F_CINV)
          ENDIF
          IF(ASSOCIATED(SELF%F_CGROUP))THEN
              CALL FIELD_DELETE(SELF%F_CGROUP)
          ENDIF
          IF(ASSOCIATED(SELF%F_XK2CG))THEN
              CALL FIELD_DELETE(SELF%F_XK2CG)
          ENDIF
          IF(ASSOCIATED(SELF%F_OMOSNH2KD))THEN
              CALL FIELD_DELETE(SELF%F_OMOSNH2KD)
          ENDIF
          IF(ASSOCIATED(SELF%F_STOKFAC))THEN
              CALL FIELD_DELETE(SELF%F_STOKFAC)
          ENDIF
          IF(ASSOCIATED(SELF%F_CIWA))THEN
              CALL FIELD_DELETE(SELF%F_CIWA)
          ENDIF
      END SUBROUTINE FREQUENCY_FINAL

      SUBROUTINE ENVIRONMENT_FIELD_INIT(SELF, INDEP, IODP, IOBND, DELLAM1, COSPHM1, DEPTH, EMAXDPT, UCUR, VCUR)
          CLASS(ENVIRONMENT_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), DIMENSION(:,:), INTENT(IN), OPTIONAL :: INDEP
          INTEGER(KIND=JWIM), DIMENSION(:,:), INTENT(IN), OPTIONAL :: IODP
          INTEGER(KIND=JWIM), DIMENSION(:,:), INTENT(IN), OPTIONAL :: IOBND
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: DELLAM1
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: COSPHM1
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: DEPTH
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: EMAXDPT
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: UCUR
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: VCUR

          IF(PRESENT(INDEP)) CALL FIELD_NEW(SELF%F_INDEP, DATA=INDEP)
          IF(PRESENT(IODP)) CALL FIELD_NEW(SELF%F_IODP, DATA=IODP)
          IF(PRESENT(IOBND)) CALL FIELD_NEW(SELF%F_IOBND, DATA=IOBND)
          IF(PRESENT(DELLAM1)) CALL FIELD_NEW(SELF%F_DELLAM1, DATA=DELLAM1)
          IF(PRESENT(COSPHM1)) CALL FIELD_NEW(SELF%F_COSPHM1, DATA=COSPHM1)
          IF(PRESENT(DEPTH)) CALL FIELD_NEW(SELF%F_DEPTH, DATA=DEPTH)
          IF(PRESENT(EMAXDPT)) CALL FIELD_NEW(SELF%F_EMAXDPT, DATA=EMAXDPT)
          IF(PRESENT(UCUR)) CALL FIELD_NEW(SELF%F_UCUR, DATA=UCUR)
          IF(PRESENT(VCUR)) CALL FIELD_NEW(SELF%F_VCUR, DATA=VCUR)
      END SUBROUTINE ENVIRONMENT_FIELD_INIT

      SUBROUTINE ENVIRONMENT_UPDATE_VIEW(SELF, BLOCK_INDEX)
          CLASS(ENVIRONMENT_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), INTENT(IN) :: BLOCK_INDEX

          IF(ASSOCIATED(SELF%F_INDEP)) SELF%INDEP => SELF%F_INDEP%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_IODP)) SELF%IODP => SELF%F_IODP%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_IOBND)) SELF%IOBND => SELF%F_IOBND%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_DELLAM1)) SELF%DELLAM1 => SELF%F_DELLAM1%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_COSPHM1)) SELF%COSPHM1 => SELF%F_COSPHM1%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_DEPTH)) SELF%DEPTH => SELF%F_DEPTH%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_EMAXDPT)) SELF%EMAXDPT => SELF%F_EMAXDPT%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_UCUR)) SELF%UCUR => SELF%F_UCUR%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_VCUR)) SELF%VCUR => SELF%F_VCUR%GET_VIEW(BLOCK_INDEX)
      END SUBROUTINE ENVIRONMENT_UPDATE_VIEW

      SUBROUTINE ENVIRONMENT_FINAL(SELF)
          CLASS(ENVIRONMENT_FIELD), INTENT(INOUT) :: SELF

          IF(ASSOCIATED(SELF%F_INDEP))THEN
              CALL FIELD_DELETE(SELF%F_INDEP)
          ENDIF
          IF(ASSOCIATED(SELF%F_IODP))THEN
              CALL FIELD_DELETE(SELF%F_IODP)
          ENDIF
          IF(ASSOCIATED(SELF%F_IOBND))THEN
              CALL FIELD_DELETE(SELF%F_IOBND)
          ENDIF
          IF(ASSOCIATED(SELF%F_DELLAM1))THEN
              CALL FIELD_DELETE(SELF%F_DELLAM1)
          ENDIF
          IF(ASSOCIATED(SELF%F_COSPHM1))THEN
              CALL FIELD_DELETE(SELF%F_COSPHM1)
          ENDIF
          IF(ASSOCIATED(SELF%F_DEPTH))THEN
              CALL FIELD_DELETE(SELF%F_DEPTH)
          ENDIF
          IF(ASSOCIATED(SELF%F_EMAXDPT))THEN
              CALL FIELD_DELETE(SELF%F_EMAXDPT)
          ENDIF
          IF(ASSOCIATED(SELF%F_UCUR))THEN
              CALL FIELD_DELETE(SELF%F_UCUR)
          ENDIF
          IF(ASSOCIATED(SELF%F_VCUR))THEN
              CALL FIELD_DELETE(SELF%F_VCUR)
          ENDIF
      END SUBROUTINE ENVIRONMENT_FINAL

      SUBROUTINE FORCING_FIELDS_FIELD_INIT(SELF, UWND, VWND, AIRD, WSTAR, CICOVER, CITHICK, LKFR, UCUR, VCUR, WSWAVE, WDWAVE,&
          & UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, XLON, YLAT)
          CLASS(FORCING_FIELDS_FIELD), INTENT(INOUT) :: SELF
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: UWND
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: VWND
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: AIRD
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: WSTAR
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: CICOVER
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: CITHICK
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: LKFR
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: UCUR
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: VCUR
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: WSWAVE
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: WDWAVE
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: UFRIC
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUW
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUWDIR
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: Z0M
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: Z0B
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: CHRNCK
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: XLON
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: YLAT

          IF(PRESENT(UWND)) CALL FIELD_NEW(SELF%F_UWND, DATA=UWND)
          IF(PRESENT(VWND)) CALL FIELD_NEW(SELF%F_VWND, DATA=VWND)
          IF(PRESENT(AIRD)) CALL FIELD_NEW(SELF%F_AIRD, DATA=AIRD)
          IF(PRESENT(WSTAR)) CALL FIELD_NEW(SELF%F_WSTAR, DATA=WSTAR)
          IF(PRESENT(CICOVER)) CALL FIELD_NEW(SELF%F_CICOVER, DATA=CICOVER)
          IF(PRESENT(CITHICK)) CALL FIELD_NEW(SELF%F_CITHICK, DATA=CITHICK)
          IF(PRESENT(LKFR)) CALL FIELD_NEW(SELF%F_LKFR, DATA=LKFR)
          IF(PRESENT(UCUR)) CALL FIELD_NEW(SELF%F_UCUR, DATA=UCUR)
          IF(PRESENT(VCUR)) CALL FIELD_NEW(SELF%F_VCUR, DATA=VCUR)
          IF(PRESENT(WSWAVE)) CALL FIELD_NEW(SELF%F_WSWAVE, DATA=WSWAVE)
          IF(PRESENT(WDWAVE)) CALL FIELD_NEW(SELF%F_WDWAVE, DATA=WDWAVE)
          IF(PRESENT(UFRIC)) CALL FIELD_NEW(SELF%F_UFRIC, DATA=UFRIC)
          IF(PRESENT(TAUW)) CALL FIELD_NEW(SELF%F_TAUW, DATA=TAUW)
          IF(PRESENT(TAUWDIR)) CALL FIELD_NEW(SELF%F_TAUWDIR, DATA=TAUWDIR)
          IF(PRESENT(Z0M)) CALL FIELD_NEW(SELF%F_Z0M, DATA=Z0M)
          IF(PRESENT(Z0B)) CALL FIELD_NEW(SELF%F_Z0B, DATA=Z0B)
          IF(PRESENT(CHRNCK)) CALL FIELD_NEW(SELF%F_CHRNCK, DATA=CHRNCK)
          IF(PRESENT(XLON)) CALL FIELD_NEW(SELF%F_XLON, DATA=XLON)
          IF(PRESENT(YLAT)) CALL FIELD_NEW(SELF%F_YLAT, DATA=YLAT)
      END SUBROUTINE FORCING_FIELDS_FIELD_INIT

      SUBROUTINE FORCING_FIELDS_UPDATE_VIEW(SELF, BLOCK_INDEX)
          CLASS(FORCING_FIELDS_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), INTENT(IN) :: BLOCK_INDEX

          IF(ASSOCIATED(SELF%F_UWND)) SELF%UWND => SELF%F_UWND%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_VWND)) SELF%VWND => SELF%F_VWND%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_AIRD)) SELF%AIRD => SELF%F_AIRD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_WSTAR)) SELF%WSTAR => SELF%F_WSTAR%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CICOVER)) SELF%CICOVER => SELF%F_CICOVER%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CITHICK)) SELF%CITHICK => SELF%F_CITHICK%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_LKFR)) SELF%LKFR => SELF%F_LKFR%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_UCUR)) SELF%UCUR => SELF%F_UCUR%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_VCUR)) SELF%VCUR => SELF%F_VCUR%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_WSWAVE)) SELF%WSWAVE => SELF%F_WSWAVE%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_WDWAVE)) SELF%WDWAVE => SELF%F_WDWAVE%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_UFRIC)) SELF%UFRIC => SELF%F_UFRIC%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUW)) SELF%TAUW => SELF%F_TAUW%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUWDIR)) SELF%TAUWDIR => SELF%F_TAUWDIR%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_Z0M)) SELF%Z0M => SELF%F_Z0M%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_Z0B)) SELF%Z0B => SELF%F_Z0B%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CHRNCK)) SELF%CHRNCK => SELF%F_CHRNCK%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_XLON)) SELF%XLON => SELF%F_XLON%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_YLAT)) SELF%YLAT => SELF%F_YLAT%GET_VIEW(BLOCK_INDEX)
      END SUBROUTINE FORCING_FIELDS_UPDATE_VIEW

      SUBROUTINE FORCING_FIELDS_FINAL(SELF)
          CLASS(FORCING_FIELDS_FIELD), INTENT(INOUT) :: SELF

          IF(ASSOCIATED(SELF%F_UWND))THEN
              CALL FIELD_DELETE(SELF%F_UWND)
          ENDIF
          IF(ASSOCIATED(SELF%F_VWND))THEN
              CALL FIELD_DELETE(SELF%F_VWND)
          ENDIF
          IF(ASSOCIATED(SELF%F_AIRD))THEN
              CALL FIELD_DELETE(SELF%F_AIRD)
          ENDIF
          IF(ASSOCIATED(SELF%F_WSTAR))THEN
              CALL FIELD_DELETE(SELF%F_WSTAR)
          ENDIF
          IF(ASSOCIATED(SELF%F_CICOVER))THEN
              CALL FIELD_DELETE(SELF%F_CICOVER)
          ENDIF
          IF(ASSOCIATED(SELF%F_CITHICK))THEN
              CALL FIELD_DELETE(SELF%F_CITHICK)
          ENDIF
          IF(ASSOCIATED(SELF%F_LKFR))THEN
              CALL FIELD_DELETE(SELF%F_LKFR)
          ENDIF
          IF(ASSOCIATED(SELF%F_UCUR))THEN
              CALL FIELD_DELETE(SELF%F_UCUR)
          ENDIF
          IF(ASSOCIATED(SELF%F_VCUR))THEN
              CALL FIELD_DELETE(SELF%F_VCUR)
          ENDIF
          IF(ASSOCIATED(SELF%F_WSWAVE))THEN
              CALL FIELD_DELETE(SELF%F_WSWAVE)
          ENDIF
          IF(ASSOCIATED(SELF%F_WDWAVE))THEN
              CALL FIELD_DELETE(SELF%F_WDWAVE)
          ENDIF
          IF(ASSOCIATED(SELF%F_UFRIC))THEN
              CALL FIELD_DELETE(SELF%F_UFRIC)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUW))THEN
              CALL FIELD_DELETE(SELF%F_TAUW)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUWDIR))THEN
              CALL FIELD_DELETE(SELF%F_TAUWDIR)
          ENDIF
          IF(ASSOCIATED(SELF%F_Z0M))THEN
              CALL FIELD_DELETE(SELF%F_Z0M)
          ENDIF
          IF(ASSOCIATED(SELF%F_Z0B))THEN
              CALL FIELD_DELETE(SELF%F_Z0B)
          ENDIF
          IF(ASSOCIATED(SELF%F_CHRNCK))THEN
              CALL FIELD_DELETE(SELF%F_CHRNCK)
          ENDIF
          IF(ASSOCIATED(SELF%F_XLON))THEN
              CALL FIELD_DELETE(SELF%F_XLON)
          ENDIF
          IF(ASSOCIATED(SELF%F_YLAT))THEN
              CALL FIELD_DELETE(SELF%F_YLAT)
          ENDIF
      END SUBROUTINE FORCING_FIELDS_FINAL

      SUBROUTINE WAVE2OCEAN_FIELD_INIT(SELF, NSWH, NMWP, NPHIEPS, NEMOPHIF, NTAUOC, NEMOTAUX, NEMOTAUY, NEMOUSTOKES, NEMOVSTOKES,&
          & NEMOSTRN, NEMOWSWAVE)
          CLASS(WAVE2OCEAN_FIELD), INTENT(INOUT) :: SELF
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NSWH
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NMWP
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NPHIEPS
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOPHIF
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NTAUOC
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOTAUX
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOTAUY
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOUSTOKES
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOVSTOKES
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOSTRN
          REAL(KIND=JWRO), DIMENSION(:,:), INTENT(IN), OPTIONAL :: NEMOWSWAVE

          IF(PRESENT(NSWH)) CALL FIELD_NEW(SELF%F_NSWH, DATA=NSWH)
          IF(PRESENT(NMWP)) CALL FIELD_NEW(SELF%F_NMWP, DATA=NMWP)
          IF(PRESENT(NPHIEPS)) CALL FIELD_NEW(SELF%F_NPHIEPS, DATA=NPHIEPS)
          IF(PRESENT(NEMOPHIF)) CALL FIELD_NEW(SELF%F_NEMOPHIF, DATA=NEMOPHIF)
          IF(PRESENT(NTAUOC)) CALL FIELD_NEW(SELF%F_NTAUOC, DATA=NTAUOC)
          IF(PRESENT(NEMOTAUX)) CALL FIELD_NEW(SELF%F_NEMOTAUX, DATA=NEMOTAUX)
          IF(PRESENT(NEMOTAUY)) CALL FIELD_NEW(SELF%F_NEMOTAUY, DATA=NEMOTAUY)
          IF(PRESENT(NEMOUSTOKES)) CALL FIELD_NEW(SELF%F_NEMOUSTOKES, DATA=NEMOUSTOKES)
          IF(PRESENT(NEMOVSTOKES)) CALL FIELD_NEW(SELF%F_NEMOVSTOKES, DATA=NEMOVSTOKES)
          IF(PRESENT(NEMOSTRN)) CALL FIELD_NEW(SELF%F_NEMOSTRN, DATA=NEMOSTRN)
          IF(PRESENT(NEMOWSWAVE)) CALL FIELD_NEW(SELF%F_NEMOWSWAVE, DATA=NEMOWSWAVE)
      END SUBROUTINE WAVE2OCEAN_FIELD_INIT

      SUBROUTINE WAVE2OCEAN_UPDATE_VIEW(SELF, BLOCK_INDEX)
          CLASS(WAVE2OCEAN_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), INTENT(IN) :: BLOCK_INDEX

          IF(ASSOCIATED(SELF%F_NSWH)) SELF%NSWH => SELF%F_NSWH%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NMWP)) SELF%NMWP => SELF%F_NMWP%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NPHIEPS)) SELF%NPHIEPS => SELF%F_NPHIEPS%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOPHIF)) SELF%NEMOPHIF => SELF%F_NEMOPHIF%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NTAUOC)) SELF%NTAUOC => SELF%F_NTAUOC%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOTAUX)) SELF%NEMOTAUX => SELF%F_NEMOTAUX%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOTAUY)) SELF%NEMOTAUY => SELF%F_NEMOTAUY%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOUSTOKES)) SELF%NEMOUSTOKES => SELF%F_NEMOUSTOKES%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOVSTOKES)) SELF%NEMOVSTOKES => SELF%F_NEMOVSTOKES%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOSTRN)) SELF%NEMOSTRN => SELF%F_NEMOSTRN%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_NEMOWSWAVE)) SELF%NEMOWSWAVE => SELF%F_NEMOWSWAVE%GET_VIEW(BLOCK_INDEX)
      END SUBROUTINE WAVE2OCEAN_UPDATE_VIEW

      SUBROUTINE WAVE2OCEAN_FINAL(SELF)
          CLASS(WAVE2OCEAN_FIELD), INTENT(INOUT) :: SELF

          IF(ASSOCIATED(SELF%F_NSWH))THEN
              CALL FIELD_DELETE(SELF%F_NSWH)
          ENDIF
          IF(ASSOCIATED(SELF%F_NMWP))THEN
              CALL FIELD_DELETE(SELF%F_NMWP)
          ENDIF
          IF(ASSOCIATED(SELF%F_NPHIEPS))THEN
              CALL FIELD_DELETE(SELF%F_NPHIEPS)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOPHIF))THEN
              CALL FIELD_DELETE(SELF%F_NEMOPHIF)
          ENDIF
          IF(ASSOCIATED(SELF%F_NTAUOC))THEN
              CALL FIELD_DELETE(SELF%F_NTAUOC)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOTAUX))THEN
              CALL FIELD_DELETE(SELF%F_NEMOTAUX)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOTAUY))THEN
              CALL FIELD_DELETE(SELF%F_NEMOTAUY)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOUSTOKES))THEN
              CALL FIELD_DELETE(SELF%F_NEMOUSTOKES)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOVSTOKES))THEN
              CALL FIELD_DELETE(SELF%F_NEMOVSTOKES)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOSTRN))THEN
              CALL FIELD_DELETE(SELF%F_NEMOSTRN)
          ENDIF
          IF(ASSOCIATED(SELF%F_NEMOWSWAVE))THEN
              CALL FIELD_DELETE(SELF%F_NEMOWSWAVE)
          ENDIF
      END SUBROUTINE WAVE2OCEAN_FINAL

      SUBROUTINE INTGT_PARAM_FIELDS_FIELD_INIT(SELF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, PHIEPS, PHIOCD, PHIAW, TAUOC, TAUXD,&
          & TAUYD, TAUOCXD, TAUOCYD, STRNMS, ALTWH, CALTWH, RALTCOR)
          CLASS(INTGT_PARAM_FIELDS_FIELD), INTENT(INOUT) :: SELF
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: WSEMEAN
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: WSFMEAN
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: USTOKES
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: VSTOKES
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: PHIEPS
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: PHIOCD
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: PHIAW
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUOC
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUXD
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUYD
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUOCXD
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: TAUOCYD
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: STRNMS
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: ALTWH
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: CALTWH
          REAL(KIND=JWRB), DIMENSION(:,:), INTENT(IN), OPTIONAL :: RALTCOR

          IF(PRESENT(WSEMEAN)) CALL FIELD_NEW(SELF%F_WSEMEAN, DATA=WSEMEAN)
          IF(PRESENT(WSFMEAN)) CALL FIELD_NEW(SELF%F_WSFMEAN, DATA=WSFMEAN)
          IF(PRESENT(USTOKES)) CALL FIELD_NEW(SELF%F_USTOKES, DATA=USTOKES)
          IF(PRESENT(VSTOKES)) CALL FIELD_NEW(SELF%F_VSTOKES, DATA=VSTOKES)
          IF(PRESENT(PHIEPS)) CALL FIELD_NEW(SELF%F_PHIEPS, DATA=PHIEPS)
          IF(PRESENT(PHIOCD)) CALL FIELD_NEW(SELF%F_PHIOCD, DATA=PHIOCD)
          IF(PRESENT(PHIAW)) CALL FIELD_NEW(SELF%F_PHIAW, DATA=PHIAW)
          IF(PRESENT(TAUOC)) CALL FIELD_NEW(SELF%F_TAUOC, DATA=TAUOC)
          IF(PRESENT(TAUXD)) CALL FIELD_NEW(SELF%F_TAUXD, DATA=TAUXD)
          IF(PRESENT(TAUYD)) CALL FIELD_NEW(SELF%F_TAUYD, DATA=TAUYD)
          IF(PRESENT(TAUOCXD)) CALL FIELD_NEW(SELF%F_TAUOCXD, DATA=TAUOCXD)
          IF(PRESENT(TAUOCYD)) CALL FIELD_NEW(SELF%F_TAUOCYD, DATA=TAUOCYD)
          IF(PRESENT(STRNMS)) CALL FIELD_NEW(SELF%F_STRNMS, DATA=STRNMS)
          IF(PRESENT(ALTWH)) CALL FIELD_NEW(SELF%F_ALTWH, DATA=ALTWH)
          IF(PRESENT(CALTWH)) CALL FIELD_NEW(SELF%F_CALTWH, DATA=CALTWH)
          IF(PRESENT(RALTCOR)) CALL FIELD_NEW(SELF%F_RALTCOR, DATA=RALTCOR)
      END SUBROUTINE INTGT_PARAM_FIELDS_FIELD_INIT

      SUBROUTINE INTGT_PARAM_FIELDS_UPDATE_VIEW(SELF, BLOCK_INDEX)
          CLASS(INTGT_PARAM_FIELDS_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), INTENT(IN) :: BLOCK_INDEX

          IF(ASSOCIATED(SELF%F_WSEMEAN)) SELF%WSEMEAN => SELF%F_WSEMEAN%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_WSFMEAN)) SELF%WSFMEAN => SELF%F_WSFMEAN%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_USTOKES)) SELF%USTOKES => SELF%F_USTOKES%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_VSTOKES)) SELF%VSTOKES => SELF%F_VSTOKES%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_PHIEPS)) SELF%PHIEPS => SELF%F_PHIEPS%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_PHIOCD)) SELF%PHIOCD => SELF%F_PHIOCD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_PHIAW)) SELF%PHIAW => SELF%F_PHIAW%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUOC)) SELF%TAUOC => SELF%F_TAUOC%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUXD)) SELF%TAUXD => SELF%F_TAUXD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUYD)) SELF%TAUYD => SELF%F_TAUYD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUOCXD)) SELF%TAUOCXD => SELF%F_TAUOCXD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_TAUOCYD)) SELF%TAUOCYD => SELF%F_TAUOCYD%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_STRNMS)) SELF%STRNMS => SELF%F_STRNMS%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_ALTWH)) SELF%ALTWH => SELF%F_ALTWH%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_CALTWH)) SELF%CALTWH => SELF%F_CALTWH%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_RALTCOR)) SELF%RALTCOR => SELF%F_RALTCOR%GET_VIEW(BLOCK_INDEX)
      END SUBROUTINE INTGT_PARAM_FIELDS_UPDATE_VIEW

      SUBROUTINE INTGT_PARAM_FIELDS_FINAL(SELF)
          CLASS(INTGT_PARAM_FIELDS_FIELD), INTENT(INOUT) :: SELF

          IF(ASSOCIATED(SELF%F_WSEMEAN))THEN
              CALL FIELD_DELETE(SELF%F_WSEMEAN)
          ENDIF
          IF(ASSOCIATED(SELF%F_WSFMEAN))THEN
              CALL FIELD_DELETE(SELF%F_WSFMEAN)
          ENDIF
          IF(ASSOCIATED(SELF%F_USTOKES))THEN
              CALL FIELD_DELETE(SELF%F_USTOKES)
          ENDIF
          IF(ASSOCIATED(SELF%F_VSTOKES))THEN
              CALL FIELD_DELETE(SELF%F_VSTOKES)
          ENDIF
          IF(ASSOCIATED(SELF%F_PHIEPS))THEN
              CALL FIELD_DELETE(SELF%F_PHIEPS)
          ENDIF
          IF(ASSOCIATED(SELF%F_PHIOCD))THEN
              CALL FIELD_DELETE(SELF%F_PHIOCD)
          ENDIF
          IF(ASSOCIATED(SELF%F_PHIAW))THEN
              CALL FIELD_DELETE(SELF%F_PHIAW)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUOC))THEN
              CALL FIELD_DELETE(SELF%F_TAUOC)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUXD))THEN
              CALL FIELD_DELETE(SELF%F_TAUXD)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUYD))THEN
              CALL FIELD_DELETE(SELF%F_TAUYD)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUOCXD))THEN
              CALL FIELD_DELETE(SELF%F_TAUOCXD)
          ENDIF
          IF(ASSOCIATED(SELF%F_TAUOCYD))THEN
              CALL FIELD_DELETE(SELF%F_TAUOCYD)
          ENDIF
          IF(ASSOCIATED(SELF%F_STRNMS))THEN
              CALL FIELD_DELETE(SELF%F_STRNMS)
          ENDIF
          IF(ASSOCIATED(SELF%F_ALTWH))THEN
              CALL FIELD_DELETE(SELF%F_ALTWH)
          ENDIF
          IF(ASSOCIATED(SELF%F_CALTWH))THEN
              CALL FIELD_DELETE(SELF%F_CALTWH)
          ENDIF
          IF(ASSOCIATED(SELF%F_RALTCOR))THEN
              CALL FIELD_DELETE(SELF%F_RALTCOR)
          ENDIF
      END SUBROUTINE INTGT_PARAM_FIELDS_FINAL

      SUBROUTINE SOURCE_CONTRIBS_FIELD_INIT(SELF, FL1, XLLWS, MIJ)
          CLASS(SOURCE_CONTRIBS_FIELD), INTENT(INOUT) :: SELF
          REAL(KIND=JWRB), DIMENSION(:,:,:,:), INTENT(IN), OPTIONAL :: FL1
          REAL(KIND=JWRB), DIMENSION(:,:,:,:), INTENT(IN), OPTIONAL :: XLLWS
          INTEGER(KIND=JWIM), DIMENSION(:,:), INTENT(IN), OPTIONAL :: MIJ

          IF(PRESENT(FL1)) CALL FIELD_NEW(SELF%F_FL1, DATA=FL1)
          IF(PRESENT(XLLWS)) CALL FIELD_NEW(SELF%F_XLLWS, DATA=XLLWS)
          IF(PRESENT(MIJ)) CALL FIELD_NEW(SELF%F_MIJ, DATA=MIJ)
      END SUBROUTINE SOURCE_CONTRIBS_FIELD_INIT

      SUBROUTINE SOURCE_CONTRIBS_UPDATE_VIEW(SELF, BLOCK_INDEX)
          CLASS(SOURCE_CONTRIBS_FIELD), INTENT(INOUT) :: SELF
          INTEGER(KIND=JWIM), INTENT(IN) :: BLOCK_INDEX

          IF(ASSOCIATED(SELF%F_FL1)) SELF%FL1 => SELF%F_FL1%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_XLLWS)) SELF%XLLWS => SELF%F_XLLWS%GET_VIEW(BLOCK_INDEX)
          IF(ASSOCIATED(SELF%F_MIJ)) SELF%MIJ => SELF%F_MIJ%GET_VIEW(BLOCK_INDEX)
      END SUBROUTINE SOURCE_CONTRIBS_UPDATE_VIEW

      SUBROUTINE SOURCE_CONTRIBS_FINAL(SELF)
          CLASS(SOURCE_CONTRIBS_FIELD), INTENT(INOUT) :: SELF

          IF(ASSOCIATED(SELF%F_FL1))THEN
              CALL FIELD_DELETE(SELF%F_FL1)
          ENDIF
          IF(ASSOCIATED(SELF%F_XLLWS))THEN
              CALL FIELD_DELETE(SELF%F_XLLWS)
          ENDIF
          IF(ASSOCIATED(SELF%F_MIJ))THEN
              CALL FIELD_DELETE(SELF%F_MIJ)
          ENDIF
      END SUBROUTINE SOURCE_CONTRIBS_FINAL

END MODULE YOWFIELD_MOD
