name: build-hpc

# Controls when the action will run
on:

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]

env:
  ECWAM_TOOLS: ${{ github.workspace }}/.github/tools
  CTEST_PARALLEL_LEVEL: 1
  CACHE_SUFFIX: v1         # Increase to force new cache to be created

jobs:
  ci-hpc:
    name: ci-hpc
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}

    strategy:
      fail-fast: false    # false: try to complete all jobs

      matrix:
        name:
          - ac-gpu nvhpc sp
          - ac-cpu intel sp

        include:
          - name: ac-gpu nvhpc sp
            site: ac-batch
            sbatch_options: |
              #SBATCH --time=00:20:00
              #SBATCH --nodes=1
              #SBATCH --ntasks=4
              #SBATCH --cpus-per-task=32
              #SBATCH --gpus-per-task=1
              #SBATCH --mem=0
              #SBATCH --qos=dg
            arch: ecmwf/hpc2020/nvhpc/24.5/hpcx-openmpi/2.19.0-cuda
            modules: ~
            build_options: --with-fckit --with-loki --with-acc --with-cuda --with-gpu-aware-mpi --with-static-linking

          - name: ac-cpu intel sp
            site: ac-batch
            sbatch_options: |
              #SBATCH --time=00:20:00
              #SBATCH --nodes=1
              #SBATCH --ntasks=4
              #SBATCH --cpus-per-task=32
              #SBATCH --hint=nomultithread
              #SBATCH --mem=60GB
              #SBATCH --qos=np
            arch: ecmwf/hpc2020/intel/2021.4.0/hpcx-openmpi/2.9.0
            modules: ~
            build_options: --with-fckit

    runs-on: [self-hosted, linux, hpc]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: ecmwf-actions/reusable-workflows/ci-hpc-generic@v2
        with:
          site: ${{ matrix.site }}
          troika_user: ${{ secrets.HPC_CI_SSH_USER }}
          sbatch_options: ${{ matrix.sbatch_options }}
          template: |
            REPO=${{ github.event.pull_request.head.repo.full_name || github.repository }}
            SHA=${{ github.event.pull_request.head.sha || github.sha }}
            { set +x; } 2>/dev/null # trace off

            echo "::group::Load modules"
            {% for module in "${{ join(matrix.modules, ',') }}".split(',') %}
              module load {{module}}
            {% endfor %}
            echo "::endgroup::"

            echo "::group::Checkout $(basename $REPO)"
            { set -x; } 2>/dev/null # trace on
            mkdir -p $REPO
            pushd $REPO
            git init
            git remote add origin ${{ github.server_url }}/$REPO
            git fetch origin $SHA
            git reset --hard FETCH_HEAD
            { set +x; } 2>/dev/null # trace off
            echo "::endgroup::"

            echo "::group::ecwam-bundle create"
            { set -x; } 2>/dev/null # trace on
            ./package/bundle/ecwam-bundle create --bundle package/bundle/bundle.yml
            { set +x; } 2>/dev/null # trace off
            echo "::endgroup::"

            echo "::group::ecwam-bundle build"
            { set -x; } 2>/dev/null # trace on
            ./package/bundle/ecwam-bundle build --arch package/bundle/arch/${{matrix.arch}} --ninja --keep-going --retry-verbose ${{matrix.build_options}}
            { set +x; } 2>/dev/null # trace off
            echo "::endgroup::"

            echo "::group::ecwam test"
            source build/env.sh
            ctest --test-dir build/ecwam
            echo "::endgroup::"
